<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class InsertDepartmentsAndMunicipalities extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $departments = [
            ['id' => '05', 'name' => 'ANTIOQUIA'],
            ['id' => '08', 'name' => 'ATLANTICO'],
            ['id' => '11', 'name' => 'BOGOTA'],
            ['id' => '13', 'name' => 'BOLIVAR'],
            ['id' => '15', 'name' => 'BOYACA'],
            ['id' => '17', 'name' => 'CALDAS'],
            ['id' => '18', 'name' => 'CAQUETA'],
            ['id' => '19', 'name' => 'CAUCA'],
            ['id' => '20', 'name' => 'CESAR'],
            ['id' => '23', 'name' => 'CORDOBA'],
            ['id' => '25', 'name' => 'CUNDINAMARCA'],
            ['id' => '27', 'name' => 'CHOCO'],
            ['id' => '41', 'name' => 'HUILA'],
            ['id' => '44', 'name' => 'LA GUAJIRA'],
            ['id' => '47', 'name' => 'MAGDALENA'],
            ['id' => '50', 'name' => 'META'],
            ['id' => '52', 'name' => 'NARIÑO'],
            ['id' => '54', 'name' => 'N. DE SANTANDER'],
            ['id' => '63', 'name' => 'QUINDIO'],
            ['id' => '66', 'name' => 'RISARALDA'],
            ['id' => '68', 'name' => 'SANTANDER'],
            ['id' => '70', 'name' => 'SUCRE'],
            ['id' => '73', 'name' => 'TOLIMA'],
            ['id' => '76', 'name' => 'VALLE DEL CAUCA'],
            ['id' => '81', 'name' => 'ARAUCA'],
            ['id' => '85', 'name' => 'CASANARE'],
            ['id' => '86', 'name' => 'PUTUMAYO'],
            ['id' => '88', 'name' => 'SAN ANDRES'],
            ['id' => '91', 'name' => 'AMAZONAS'],
            ['id' => '94', 'name' => 'GUAINIA'],
            ['id' => '95', 'name' => 'GUAVIARE'],
            ['id' => '97', 'name' => 'VAUPES'],
            ['id' => '99', 'name' => 'VICHADA']
        ];

        $municipalities = [
            ['id' => '05001', 'name' => 'MEDELLIN', 'department_id' => '05'],
            ['id' => '05002', 'name' => 'ABEJORRAL', 'department_id' => '05'],
            ['id' => '05004', 'name' => 'ABRIAQUI', 'department_id' => '05'],
            ['id' => '05021', 'name' => 'ALEJANDRIA', 'department_id' => '05'],
            ['id' => '05030', 'name' => 'AMAGA', 'department_id' => '05'],
            ['id' => '05031', 'name' => 'AMALFI', 'department_id' => '05'],
            ['id' => '05034', 'name' => 'ANDES', 'department_id' => '05'],
            ['id' => '05036', 'name' => 'ANGELOPOLIS', 'department_id' => '05'],
            ['id' => '05038', 'name' => 'ANGOSTURA', 'department_id' => '05'],
            ['id' => '05040', 'name' => 'ANORI', 'department_id' => '05'],
            ['id' => '05042', 'name' => 'SANTAFE DE ANTIOQUIA', 'department_id' => '05'],
            ['id' => '05044', 'name' => 'ANZA', 'department_id' => '05'],
            ['id' => '05045', 'name' => 'APARTADO', 'department_id' => '05'],
            ['id' => '05051', 'name' => 'ARBOLETES', 'department_id' => '05'],
            ['id' => '05055', 'name' => 'ARGELIA', 'department_id' => '05'],
            ['id' => '05059', 'name' => 'ARMENIA', 'department_id' => '05'],
            ['id' => '05079', 'name' => 'BARBOSA', 'department_id' => '05'],
            ['id' => '05086', 'name' => 'BELMIRA', 'department_id' => '05'],
            ['id' => '05088', 'name' => 'BELLO', 'department_id' => '05'],
            ['id' => '05091', 'name' => 'BETANIA', 'department_id' => '05'],
            ['id' => '05093', 'name' => 'BETULIA', 'department_id' => '05'],
            ['id' => '05101', 'name' => 'CIUDAD BOLIVAR', 'department_id' => '05'],
            ['id' => '05107', 'name' => 'BRICEÑO', 'department_id' => '05'],
            ['id' => '05113', 'name' => 'BURITICA', 'department_id' => '05'],
            ['id' => '05120', 'name' => 'CACERES', 'department_id' => '05'],
            ['id' => '05125', 'name' => 'CAICEDO', 'department_id' => '05'],
            ['id' => '05129', 'name' => 'CALDAS', 'department_id' => '05'],
            ['id' => '05134', 'name' => 'CAMPAMENTO', 'department_id' => '05'],
            ['id' => '05138', 'name' => 'CAÑASGORDAS', 'department_id' => '05'],
            ['id' => '05142', 'name' => 'CARACOLI', 'department_id' => '05'],
            ['id' => '05145', 'name' => 'CARAMANTA', 'department_id' => '05'],
            ['id' => '05147', 'name' => 'CAREPA', 'department_id' => '05'],
            ['id' => '05148', 'name' => 'EL CARMEN DE VIBORAL', 'department_id' => '05'],
            ['id' => '05150', 'name' => 'CAROLINA', 'department_id' => '05'],
            ['id' => '05154', 'name' => 'CAUCASIA', 'department_id' => '05'],
            ['id' => '05172', 'name' => 'CHIGORODO', 'department_id' => '05'],
            ['id' => '05190', 'name' => 'CISNEROS', 'department_id' => '05'],
            ['id' => '05197', 'name' => 'COCORNA', 'department_id' => '05'],
            ['id' => '05206', 'name' => 'CONCEPCION', 'department_id' => '05'],
            ['id' => '05209', 'name' => 'CONCORDIA', 'department_id' => '05'],
            ['id' => '05212', 'name' => 'COPACABANA', 'department_id' => '05'],
            ['id' => '05234', 'name' => 'DABEIBA', 'department_id' => '05'],
            ['id' => '05237', 'name' => 'DON MATIAS', 'department_id' => '05'],
            ['id' => '05240', 'name' => 'EBEJICO', 'department_id' => '05'],
            ['id' => '05250', 'name' => 'EL BAGRE', 'department_id' => '05'],
            ['id' => '05264', 'name' => 'ENTRERRIOS', 'department_id' => '05'],
            ['id' => '05266', 'name' => 'ENVIGADO', 'department_id' => '05'],
            ['id' => '05282', 'name' => 'FREDONIA', 'department_id' => '05'],
            ['id' => '05284', 'name' => 'FRONTINO', 'department_id' => '05'],
            ['id' => '05306', 'name' => 'GIRALDO', 'department_id' => '05'],
            ['id' => '05308', 'name' => 'GIRARDOTA', 'department_id' => '05'],
            ['id' => '05310', 'name' => 'GOMEZ PLATA', 'department_id' => '05'],
            ['id' => '05313', 'name' => 'GRANADA', 'department_id' => '05'],
            ['id' => '05315', 'name' => 'GUADALUPE', 'department_id' => '05'],
            ['id' => '05318', 'name' => 'GUARNE', 'department_id' => '05'],
            ['id' => '05321', 'name' => 'GUATAPE', 'department_id' => '05'],
            ['id' => '05347', 'name' => 'HELICONIA', 'department_id' => '05'],
            ['id' => '05353', 'name' => 'HISPANIA', 'department_id' => '05'],
            ['id' => '05360', 'name' => 'ITAGUI', 'department_id' => '05'],
            ['id' => '05361', 'name' => 'ITUANGO', 'department_id' => '05'],
            ['id' => '05364', 'name' => 'JARDIN', 'department_id' => '05'],
            ['id' => '05368', 'name' => 'JERICO', 'department_id' => '05'],
            ['id' => '05376', 'name' => 'LA CEJA', 'department_id' => '05'],
            ['id' => '05380', 'name' => 'LA ESTRELLA', 'department_id' => '05'],
            ['id' => '05390', 'name' => 'LA PINTADA', 'department_id' => '05'],
            ['id' => '05400', 'name' => 'LA UNION', 'department_id' => '05'],
            ['id' => '05411', 'name' => 'LIBORINA', 'department_id' => '05'],
            ['id' => '05425', 'name' => 'MACEO', 'department_id' => '05'],
            ['id' => '05440', 'name' => 'MARINILLA', 'department_id' => '05'],
            ['id' => '05467', 'name' => 'MONTEBELLO', 'department_id' => '05'],
            ['id' => '05475', 'name' => 'MURINDO', 'department_id' => '05'],
            ['id' => '05480', 'name' => 'MUTATA', 'department_id' => '05'],
            ['id' => '05483', 'name' => 'NARIÑO', 'department_id' => '05'],
            ['id' => '05490', 'name' => 'NECOCLI', 'department_id' => '05'],
            ['id' => '05495', 'name' => 'NECHI', 'department_id' => '05'],
            ['id' => '05501', 'name' => 'OLAYA', 'department_id' => '05'],
            ['id' => '05541', 'name' => 'PEÐOL', 'department_id' => '05'],
            ['id' => '05543', 'name' => 'PEQUE', 'department_id' => '05'],
            ['id' => '05576', 'name' => 'PUEBLORRICO', 'department_id' => '05'],
            ['id' => '05579', 'name' => 'PUERTO BERRIO', 'department_id' => '05'],
            ['id' => '05585', 'name' => 'PUERTO NARE', 'department_id' => '05'],
            ['id' => '05591', 'name' => 'PUERTO TRIUNFO', 'department_id' => '05'],
            ['id' => '05604', 'name' => 'REMEDIOS', 'department_id' => '05'],
            ['id' => '05607', 'name' => 'RETIRO', 'department_id' => '05'],
            ['id' => '05615', 'name' => 'RIONEGRO', 'department_id' => '05'],
            ['id' => '05628', 'name' => 'SABANALARGA', 'department_id' => '05'],
            ['id' => '05631', 'name' => 'SABANETA', 'department_id' => '05'],
            ['id' => '05642', 'name' => 'SALGAR', 'department_id' => '05'],
            ['id' => '05647', 'name' => 'SAN ANDRES DE CUERQUIA', 'department_id' => '05'],
            ['id' => '05649', 'name' => 'SAN CARLOS', 'department_id' => '05'],
            ['id' => '05652', 'name' => 'SAN FRANCISCO', 'department_id' => '05'],
            ['id' => '05656', 'name' => 'SAN JERONIMO', 'department_id' => '05'],
            ['id' => '05658', 'name' => 'SAN JOSE DE LA MONTAÑA', 'department_id' => '05'],
            ['id' => '05659', 'name' => 'SAN JUAN DE URABA', 'department_id' => '05'],
            ['id' => '05660', 'name' => 'SAN LUIS', 'department_id' => '05'],
            ['id' => '05664', 'name' => 'SAN PEDRO', 'department_id' => '05'],
            ['id' => '05665', 'name' => 'SAN PEDRO DE URABA', 'department_id' => '05'],
            ['id' => '05667', 'name' => 'SAN RAFAEL', 'department_id' => '05'],
            ['id' => '05670', 'name' => 'SAN ROQUE', 'department_id' => '05'],
            ['id' => '05674', 'name' => 'SAN VICENTE', 'department_id' => '05'],
            ['id' => '05679', 'name' => 'SANTA BARBARA', 'department_id' => '05'],
            ['id' => '05686', 'name' => 'SANTA ROSA DE OSOS', 'department_id' => '05'],
            ['id' => '05690', 'name' => 'SANTO DOMINGO', 'department_id' => '05'],
            ['id' => '05697', 'name' => 'EL SANTUARIO', 'department_id' => '05'],
            ['id' => '05736', 'name' => 'SEGOVIA', 'department_id' => '05'],
            ['id' => '05756', 'name' => 'SONSON', 'department_id' => '05'],
            ['id' => '05761', 'name' => 'SOPETRAN', 'department_id' => '05'],
            ['id' => '05789', 'name' => 'TAMESIS', 'department_id' => '05'],
            ['id' => '05790', 'name' => 'TARAZA', 'department_id' => '05'],
            ['id' => '05792', 'name' => 'TARSO', 'department_id' => '05'],
            ['id' => '05809', 'name' => 'TITIRIBI', 'department_id' => '05'],
            ['id' => '05819', 'name' => 'TOLEDO', 'department_id' => '05'],
            ['id' => '05837', 'name' => 'TURBO', 'department_id' => '05'],
            ['id' => '05842', 'name' => 'URAMITA', 'department_id' => '05'],
            ['id' => '05847', 'name' => 'URRAO', 'department_id' => '05'],
            ['id' => '05854', 'name' => 'VALDIVIA', 'department_id' => '05'],
            ['id' => '05856', 'name' => 'VALPARAISO', 'department_id' => '05'],
            ['id' => '05858', 'name' => 'VEGACHI', 'department_id' => '05'],
            ['id' => '05861', 'name' => 'VENECIA', 'department_id' => '05'],
            ['id' => '05873', 'name' => 'VIGIA DEL FUERTE', 'department_id' => '05'],
            ['id' => '05885', 'name' => 'YALI', 'department_id' => '05'],
            ['id' => '05887', 'name' => 'YARUMAL', 'department_id' => '05'],
            ['id' => '05890', 'name' => 'YOLOMBO', 'department_id' => '05'],
            ['id' => '05893', 'name' => 'YONDO', 'department_id' => '05'],
            ['id' => '05895', 'name' => 'ZARAGOZA', 'department_id' => '05'],
            ['id' => '08001', 'name' => 'BARRANQUILLA', 'department_id' => '08'],
            ['id' => '08078', 'name' => 'BARANOA', 'department_id' => '08'],
            ['id' => '08137', 'name' => 'CAMPO DE LA CRUZ', 'department_id' => '08'],
            ['id' => '08141', 'name' => 'CANDELARIA', 'department_id' => '08'],
            ['id' => '08296', 'name' => 'GALAPA', 'department_id' => '08'],
            ['id' => '08372', 'name' => 'JUAN DE ACOSTA', 'department_id' => '08'],
            ['id' => '08421', 'name' => 'LURUACO', 'department_id' => '08'],
            ['id' => '08433', 'name' => 'MALAMBO', 'department_id' => '08'],
            ['id' => '08436', 'name' => 'MANATI', 'department_id' => '08'],
            ['id' => '08520', 'name' => 'PALMAR DE VARELA', 'department_id' => '08'],
            ['id' => '08549', 'name' => 'PIOJO', 'department_id' => '08'],
            ['id' => '08558', 'name' => 'POLONUEVO', 'department_id' => '08'],
            ['id' => '08560', 'name' => 'PONEDERA', 'department_id' => '08'],
            ['id' => '08573', 'name' => 'PUERTO COLOMBIA', 'department_id' => '08'],
            ['id' => '08606', 'name' => 'REPELON', 'department_id' => '08'],
            ['id' => '08634', 'name' => 'SABANAGRANDE', 'department_id' => '08'],
            ['id' => '08638', 'name' => 'SABANALARGA', 'department_id' => '08'],
            ['id' => '08675', 'name' => 'SANTA LUCIA', 'department_id' => '08'],
            ['id' => '08685', 'name' => 'SANTO TOMAS', 'department_id' => '08'],
            ['id' => '08758', 'name' => 'SOLEDAD', 'department_id' => '08'],
            ['id' => '08770', 'name' => 'SUAN', 'department_id' => '08'],
            ['id' => '08832', 'name' => 'TUBARA', 'department_id' => '08'],
            ['id' => '08849', 'name' => 'USIACURI', 'department_id' => '08'],
            ['id' => '11001', 'name' => 'BOGOTA, D.C.', 'department_id' => '11'],
            ['id' => '13001', 'name' => 'CARTAGENA', 'department_id' => '13'],
            ['id' => '13006', 'name' => 'ACHI', 'department_id' => '13'],
            ['id' => '13030', 'name' => 'ALTOS DEL ROSARIO', 'department_id' => '13'],
            ['id' => '13042', 'name' => 'ARENAL', 'department_id' => '13'],
            ['id' => '13052', 'name' => 'ARJONA', 'department_id' => '13'],
            ['id' => '13062', 'name' => 'ARROYOHONDO', 'department_id' => '13'],
            ['id' => '13074', 'name' => 'BARRANCO DE LOBA', 'department_id' => '13'],
            ['id' => '13140', 'name' => 'CALAMAR', 'department_id' => '13'],
            ['id' => '13160', 'name' => 'CANTAGALLO', 'department_id' => '13'],
            ['id' => '13188', 'name' => 'CICUCO', 'department_id' => '13'],
            ['id' => '13212', 'name' => 'CORDOBA', 'department_id' => '13'],
            ['id' => '13222', 'name' => 'CLEMENCIA', 'department_id' => '13'],
            ['id' => '13244', 'name' => 'EL CARMEN DE BOLIVAR', 'department_id' => '13'],
            ['id' => '13248', 'name' => 'EL GUAMO', 'department_id' => '13'],
            ['id' => '13268', 'name' => 'EL PEÑON', 'department_id' => '13'],
            ['id' => '13300', 'name' => 'HATILLO DE LOBA', 'department_id' => '13'],
            ['id' => '13430', 'name' => 'MAGANGUE', 'department_id' => '13'],
            ['id' => '13433', 'name' => 'MAHATES', 'department_id' => '13'],
            ['id' => '13440', 'name' => 'MARGARITA', 'department_id' => '13'],
            ['id' => '13442', 'name' => 'MARIA LA BAJA', 'department_id' => '13'],
            ['id' => '13458', 'name' => 'MONTECRISTO', 'department_id' => '13'],
            ['id' => '13468', 'name' => 'MOMPOS', 'department_id' => '13'],
            ['id' => '13490', 'name' => 'NOROSI', 'department_id' => '13'],
            ['id' => '13473', 'name' => 'MORALES', 'department_id' => '13'],
            ['id' => '13549', 'name' => 'PINILLOS', 'department_id' => '13'],
            ['id' => '13580', 'name' => 'REGIDOR', 'department_id' => '13'],
            ['id' => '13600', 'name' => 'RIO VIEJO', 'department_id' => '13'],
            ['id' => '13620', 'name' => 'SAN CRISTOBAL', 'department_id' => '13'],
            ['id' => '13647', 'name' => 'SAN ESTANISLAO', 'department_id' => '13'],
            ['id' => '13650', 'name' => 'SAN FERNANDO', 'department_id' => '13'],
            ['id' => '13654', 'name' => 'SAN JACINTO', 'department_id' => '13'],
            ['id' => '13655', 'name' => 'SAN JACINTO DEL CAUCA', 'department_id' => '13'],
            ['id' => '13657', 'name' => 'SAN JUAN NEPOMUCENO', 'department_id' => '13'],
            ['id' => '13667', 'name' => 'SAN MARTIN DE LOBA', 'department_id' => '13'],
            ['id' => '13670', 'name' => 'SAN PABLO', 'department_id' => '13'],
            ['id' => '13673', 'name' => 'SANTA CATALINA', 'department_id' => '13'],
            ['id' => '13683', 'name' => 'SANTA ROSA', 'department_id' => '13'],
            ['id' => '13688', 'name' => 'SANTA ROSA DEL SUR', 'department_id' => '13'],
            ['id' => '13744', 'name' => 'SIMITI', 'department_id' => '13'],
            ['id' => '13760', 'name' => 'SOPLAVIENTO', 'department_id' => '13'],
            ['id' => '13780', 'name' => 'TALAIGUA NUEVO', 'department_id' => '13'],
            ['id' => '13810', 'name' => 'TIQUISIO', 'department_id' => '13'],
            ['id' => '13836', 'name' => 'TURBACO', 'department_id' => '13'],
            ['id' => '13838', 'name' => 'TURBANA', 'department_id' => '13'],
            ['id' => '13873', 'name' => 'VILLANUEVA', 'department_id' => '13'],
            ['id' => '13894', 'name' => 'ZAMBRANO', 'department_id' => '13'],
            ['id' => '15001', 'name' => 'TUNJA', 'department_id' => '15'],
            ['id' => '15022', 'name' => 'ALMEIDA', 'department_id' => '15'],
            ['id' => '15047', 'name' => 'AQUITANIA', 'department_id' => '15'],
            ['id' => '15051', 'name' => 'ARCABUCO', 'department_id' => '15'],
            ['id' => '15087', 'name' => 'BELEN', 'department_id' => '15'],
            ['id' => '15090', 'name' => 'BERBEO', 'department_id' => '15'],
            ['id' => '15092', 'name' => 'BETEITIVA', 'department_id' => '15'],
            ['id' => '15097', 'name' => 'BOAVITA', 'department_id' => '15'],
            ['id' => '15104', 'name' => 'BOYACA', 'department_id' => '15'],
            ['id' => '15106', 'name' => 'BRICEÑO', 'department_id' => '15'],
            ['id' => '15109', 'name' => 'BUENAVISTA', 'department_id' => '15'],
            ['id' => '15114', 'name' => 'BUSBANZA', 'department_id' => '15'],
            ['id' => '15131', 'name' => 'CALDAS', 'department_id' => '15'],
            ['id' => '15135', 'name' => 'CAMPOHERMOSO', 'department_id' => '15'],
            ['id' => '15162', 'name' => 'CERINZA', 'department_id' => '15'],
            ['id' => '15172', 'name' => 'CHINAVITA', 'department_id' => '15'],
            ['id' => '15176', 'name' => 'CHIQUINQUIRA', 'department_id' => '15'],
            ['id' => '15180', 'name' => 'CHISCAS', 'department_id' => '15'],
            ['id' => '15183', 'name' => 'CHITA', 'department_id' => '15'],
            ['id' => '15185', 'name' => 'CHITARAQUE', 'department_id' => '15'],
            ['id' => '15187', 'name' => 'CHIVATA', 'department_id' => '15'],
            ['id' => '15189', 'name' => 'CIENEGA', 'department_id' => '15'],
            ['id' => '15204', 'name' => 'COMBITA', 'department_id' => '15'],
            ['id' => '15212', 'name' => 'COPER', 'department_id' => '15'],
            ['id' => '15215', 'name' => 'CORRALES', 'department_id' => '15'],
            ['id' => '15218', 'name' => 'COVARACHIA', 'department_id' => '15'],
            ['id' => '15223', 'name' => 'CUBARA', 'department_id' => '15'],
            ['id' => '15224', 'name' => 'CUCAITA', 'department_id' => '15'],
            ['id' => '15226', 'name' => 'CUITIVA', 'department_id' => '15'],
            ['id' => '15232', 'name' => 'CHIQUIZA', 'department_id' => '15'],
            ['id' => '15236', 'name' => 'CHIVOR', 'department_id' => '15'],
            ['id' => '15238', 'name' => 'DUITAMA', 'department_id' => '15'],
            ['id' => '15244', 'name' => 'EL COCUY', 'department_id' => '15'],
            ['id' => '15248', 'name' => 'EL ESPINO', 'department_id' => '15'],
            ['id' => '15272', 'name' => 'FIRAVITOBA', 'department_id' => '15'],
            ['id' => '15276', 'name' => 'FLORESTA', 'department_id' => '15'],
            ['id' => '15293', 'name' => 'GACHANTIVA', 'department_id' => '15'],
            ['id' => '15296', 'name' => 'GAMEZA', 'department_id' => '15'],
            ['id' => '15299', 'name' => 'GARAGOA', 'department_id' => '15'],
            ['id' => '15317', 'name' => 'GUACAMAYAS', 'department_id' => '15'],
            ['id' => '15322', 'name' => 'GUATEQUE', 'department_id' => '15'],
            ['id' => '15325', 'name' => 'GUAYATA', 'department_id' => '15'],
            ['id' => '15332', 'name' => 'GsICAN', 'department_id' => '15'],
            ['id' => '15362', 'name' => 'IZA', 'department_id' => '15'],
            ['id' => '15367', 'name' => 'JENESANO', 'department_id' => '15'],
            ['id' => '15368', 'name' => 'JERICO', 'department_id' => '15'],
            ['id' => '15377', 'name' => 'LABRANZAGRANDE', 'department_id' => '15'],
            ['id' => '15380', 'name' => 'LA CAPILLA', 'department_id' => '15'],
            ['id' => '15401', 'name' => 'LA VICTORIA', 'department_id' => '15'],
            ['id' => '15403', 'name' => 'LA UVITA', 'department_id' => '15'],
            ['id' => '15407', 'name' => 'VILLA DE LEYVA', 'department_id' => '15'],
            ['id' => '15425', 'name' => 'MACANAL', 'department_id' => '15'],
            ['id' => '15442', 'name' => 'MARIPI', 'department_id' => '15'],
            ['id' => '15455', 'name' => 'MIRAFLORES', 'department_id' => '15'],
            ['id' => '15464', 'name' => 'MONGUA', 'department_id' => '15'],
            ['id' => '15466', 'name' => 'MONGUI', 'department_id' => '15'],
            ['id' => '15469', 'name' => 'MONIQUIRA', 'department_id' => '15'],
            ['id' => '15476', 'name' => 'MOTAVITA', 'department_id' => '15'],
            ['id' => '15480', 'name' => 'MUZO', 'department_id' => '15'],
            ['id' => '15491', 'name' => 'NOBSA', 'department_id' => '15'],
            ['id' => '15494', 'name' => 'NUEVO COLON', 'department_id' => '15'],
            ['id' => '15500', 'name' => 'OICATA', 'department_id' => '15'],
            ['id' => '15507', 'name' => 'OTANCHE', 'department_id' => '15'],
            ['id' => '15511', 'name' => 'PACHAVITA', 'department_id' => '15'],
            ['id' => '15514', 'name' => 'PAEZ', 'department_id' => '15'],
            ['id' => '15516', 'name' => 'PAIPA', 'department_id' => '15'],
            ['id' => '15518', 'name' => 'PAJARITO', 'department_id' => '15'],
            ['id' => '15522', 'name' => 'PANQUEBA', 'department_id' => '15'],
            ['id' => '15531', 'name' => 'PAUNA', 'department_id' => '15'],
            ['id' => '15533', 'name' => 'PAYA', 'department_id' => '15'],
            ['id' => '15537', 'name' => 'PAZ DE RIO', 'department_id' => '15'],
            ['id' => '15542', 'name' => 'PESCA', 'department_id' => '15'],
            ['id' => '15550', 'name' => 'PISBA', 'department_id' => '15'],
            ['id' => '15572', 'name' => 'PUERTO BOYACA', 'department_id' => '15'],
            ['id' => '15580', 'name' => 'QUIPAMA', 'department_id' => '15'],
            ['id' => '15599', 'name' => 'RAMIRIQUI', 'department_id' => '15'],
            ['id' => '15600', 'name' => 'RAQUIRA', 'department_id' => '15'],
            ['id' => '15621', 'name' => 'RONDON', 'department_id' => '15'],
            ['id' => '15632', 'name' => 'SABOYA', 'department_id' => '15'],
            ['id' => '15638', 'name' => 'SACHICA', 'department_id' => '15'],
            ['id' => '15646', 'name' => 'SAMACA', 'department_id' => '15'],
            ['id' => '15660', 'name' => 'SAN EDUARDO', 'department_id' => '15'],
            ['id' => '15664', 'name' => 'SAN JOSE DE PARE', 'department_id' => '15'],
            ['id' => '15667', 'name' => 'SAN LUIS DE GACENO', 'department_id' => '15'],
            ['id' => '15673', 'name' => 'SAN MATEO', 'department_id' => '15'],
            ['id' => '15676', 'name' => 'SAN MIGUEL DE SEMA', 'department_id' => '15'],
            ['id' => '15681', 'name' => 'SAN PABLO DE BORBUR', 'department_id' => '15'],
            ['id' => '15686', 'name' => 'SANTANA', 'department_id' => '15'],
            ['id' => '15690', 'name' => 'SANTA MARIA', 'department_id' => '15'],
            ['id' => '15693', 'name' => 'SANTA ROSA DE VITERBO', 'department_id' => '15'],
            ['id' => '15696', 'name' => 'SANTA SOFIA', 'department_id' => '15'],
            ['id' => '15720', 'name' => 'SATIVANORTE', 'department_id' => '15'],
            ['id' => '15723', 'name' => 'SATIVASUR', 'department_id' => '15'],
            ['id' => '15740', 'name' => 'SIACHOQUE', 'department_id' => '15'],
            ['id' => '15753', 'name' => 'SOATA', 'department_id' => '15'],
            ['id' => '15755', 'name' => 'SOCOTA', 'department_id' => '15'],
            ['id' => '15757', 'name' => 'SOCHA', 'department_id' => '15'],
            ['id' => '15759', 'name' => 'SOGAMOSO', 'department_id' => '15'],
            ['id' => '15761', 'name' => 'SOMONDOCO', 'department_id' => '15'],
            ['id' => '15762', 'name' => 'SORA', 'department_id' => '15'],
            ['id' => '15763', 'name' => 'SOTAQUIRA', 'department_id' => '15'],
            ['id' => '15764', 'name' => 'SORACA', 'department_id' => '15'],
            ['id' => '15774', 'name' => 'SUSACON', 'department_id' => '15'],
            ['id' => '15776', 'name' => 'SUTAMARCHAN', 'department_id' => '15'],
            ['id' => '15778', 'name' => 'SUTATENZA', 'department_id' => '15'],
            ['id' => '15790', 'name' => 'TASCO', 'department_id' => '15'],
            ['id' => '15798', 'name' => 'TENZA', 'department_id' => '15'],
            ['id' => '15804', 'name' => 'TIBANA', 'department_id' => '15'],
            ['id' => '15806', 'name' => 'TIBASOSA', 'department_id' => '15'],
            ['id' => '15808', 'name' => 'TINJACA', 'department_id' => '15'],
            ['id' => '15810', 'name' => 'TIPACOQUE', 'department_id' => '15'],
            ['id' => '15814', 'name' => 'TOCA', 'department_id' => '15'],
            ['id' => '15816', 'name' => 'TOGsI', 'department_id' => '15'],
            ['id' => '15820', 'name' => 'TOPAGA', 'department_id' => '15'],
            ['id' => '15822', 'name' => 'TOTA', 'department_id' => '15'],
            ['id' => '15832', 'name' => 'TUNUNGUA', 'department_id' => '15'],
            ['id' => '15835', 'name' => 'TURMEQUE', 'department_id' => '15'],
            ['id' => '15837', 'name' => 'TUTA', 'department_id' => '15'],
            ['id' => '15839', 'name' => 'TUTAZA', 'department_id' => '15'],
            ['id' => '15842', 'name' => 'UMBITA', 'department_id' => '15'],
            ['id' => '15861', 'name' => 'VENTAQUEMADA', 'department_id' => '15'],
            ['id' => '15879', 'name' => 'VIRACACHA', 'department_id' => '15'],
            ['id' => '15897', 'name' => 'ZETAQUIRA', 'department_id' => '15'],
            ['id' => '17001', 'name' => 'MANIZALES', 'department_id' => '17'],
            ['id' => '17013', 'name' => 'AGUADAS', 'department_id' => '17'],
            ['id' => '17042', 'name' => 'ANSERMA', 'department_id' => '17'],
            ['id' => '17050', 'name' => 'ARANZAZU', 'department_id' => '17'],
            ['id' => '17088', 'name' => 'BELALCAZAR', 'department_id' => '17'],
            ['id' => '17174', 'name' => 'CHINCHINA', 'department_id' => '17'],
            ['id' => '17272', 'name' => 'FILADELFIA', 'department_id' => '17'],
            ['id' => '17380', 'name' => 'LA DORADA', 'department_id' => '17'],
            ['id' => '17388', 'name' => 'LA MERCED', 'department_id' => '17'],
            ['id' => '17433', 'name' => 'MANZANARES', 'department_id' => '17'],
            ['id' => '17442', 'name' => 'MARMATO', 'department_id' => '17'],
            ['id' => '17444', 'name' => 'MARQUETALIA', 'department_id' => '17'],
            ['id' => '17446', 'name' => 'MARULANDA', 'department_id' => '17'],
            ['id' => '17486', 'name' => 'NEIRA', 'department_id' => '17'],
            ['id' => '17495', 'name' => 'NORCASIA', 'department_id' => '17'],
            ['id' => '17513', 'name' => 'PACORA', 'department_id' => '17'],
            ['id' => '17524', 'name' => 'PALESTINA', 'department_id' => '17'],
            ['id' => '17541', 'name' => 'PENSILVANIA', 'department_id' => '17'],
            ['id' => '17614', 'name' => 'RIOSUCIO', 'department_id' => '17'],
            ['id' => '17616', 'name' => 'RISARALDA', 'department_id' => '17'],
            ['id' => '17653', 'name' => 'SALAMINA', 'department_id' => '17'],
            ['id' => '17662', 'name' => 'SAMANA', 'department_id' => '17'],
            ['id' => '17665', 'name' => 'SAN JOSE', 'department_id' => '17'],
            ['id' => '17777', 'name' => 'SUPIA', 'department_id' => '17'],
            ['id' => '17867', 'name' => 'VICTORIA', 'department_id' => '17'],
            ['id' => '17873', 'name' => 'VILLAMARIA', 'department_id' => '17'],
            ['id' => '17877', 'name' => 'VITERBO', 'department_id' => '17'],
            ['id' => '18001', 'name' => 'FLORENCIA', 'department_id' => '18'],
            ['id' => '18029', 'name' => 'ALBANIA', 'department_id' => '18'],
            ['id' => '18094', 'name' => 'BELEN DE LOS ANDAQUIES', 'department_id' => '18'],
            ['id' => '18150', 'name' => 'CARTAGENA DEL CHAIRA', 'department_id' => '18'],
            ['id' => '18205', 'name' => 'CURILLO', 'department_id' => '18'],
            ['id' => '18247', 'name' => 'EL DONCELLO', 'department_id' => '18'],
            ['id' => '18256', 'name' => 'EL PAUJIL', 'department_id' => '18'],
            ['id' => '18410', 'name' => 'LA MONTAÑITA', 'department_id' => '18'],
            ['id' => '18460', 'name' => 'MILAN', 'department_id' => '18'],
            ['id' => '18479', 'name' => 'MORELIA', 'department_id' => '18'],
            ['id' => '18592', 'name' => 'PUERTO RICO', 'department_id' => '18'],
            ['id' => '18610', 'name' => 'SAN JOSE DEL FRAGUA', 'department_id' => '18'],
            ['id' => '18753', 'name' => 'SAN VICENTE DEL CAGUAN', 'department_id' => '18'],
            ['id' => '18756', 'name' => 'SOLANO', 'department_id' => '18'],
            ['id' => '18785', 'name' => 'SOLITA', 'department_id' => '18'],
            ['id' => '18860', 'name' => 'VALPARAISO', 'department_id' => '18'],
            ['id' => '19001', 'name' => 'POPAYAN', 'department_id' => '19'],
            ['id' => '19022', 'name' => 'ALMAGUER', 'department_id' => '19'],
            ['id' => '19050', 'name' => 'ARGELIA', 'department_id' => '19'],
            ['id' => '19075', 'name' => 'BALBOA', 'department_id' => '19'],
            ['id' => '19100', 'name' => 'BOLIVAR', 'department_id' => '19'],
            ['id' => '19110', 'name' => 'BUENOS AIRES', 'department_id' => '19'],
            ['id' => '19130', 'name' => 'CAJIBIO', 'department_id' => '19'],
            ['id' => '19137', 'name' => 'CALDONO', 'department_id' => '19'],
            ['id' => '19142', 'name' => 'CALOTO', 'department_id' => '19'],
            ['id' => '19212', 'name' => 'CORINTO', 'department_id' => '19'],
            ['id' => '19256', 'name' => 'EL TAMBO', 'department_id' => '19'],
            ['id' => '19290', 'name' => 'FLORENCIA', 'department_id' => '19'],
            ['id' => '19300', 'name' => 'GUACHENE', 'department_id' => '19'],
            ['id' => '19318', 'name' => 'GUAPI', 'department_id' => '19'],
            ['id' => '19355', 'name' => 'INZA', 'department_id' => '19'],
            ['id' => '19364', 'name' => 'JAMBALO', 'department_id' => '19'],
            ['id' => '19392', 'name' => 'LA SIERRA', 'department_id' => '19'],
            ['id' => '19397', 'name' => 'LA VEGA', 'department_id' => '19'],
            ['id' => '19418', 'name' => 'LOPEZ', 'department_id' => '19'],
            ['id' => '19450', 'name' => 'MERCADERES', 'department_id' => '19'],
            ['id' => '19455', 'name' => 'MIRANDA', 'department_id' => '19'],
            ['id' => '19473', 'name' => 'MORALES', 'department_id' => '19'],
            ['id' => '19513', 'name' => 'PADILLA', 'department_id' => '19'],
            ['id' => '19517', 'name' => 'PAEZ', 'department_id' => '19'],
            ['id' => '19532', 'name' => 'PATIA', 'department_id' => '19'],
            ['id' => '19533', 'name' => 'PIAMONTE', 'department_id' => '19'],
            ['id' => '19548', 'name' => 'PIENDAMO', 'department_id' => '19'],
            ['id' => '19573', 'name' => 'PUERTO TEJADA', 'department_id' => '19'],
            ['id' => '19585', 'name' => 'PURACE', 'department_id' => '19'],
            ['id' => '19622', 'name' => 'ROSAS', 'department_id' => '19'],
            ['id' => '19693', 'name' => 'SAN SEBASTIAN', 'department_id' => '19'],
            ['id' => '19698', 'name' => 'SANTANDER DE QUILICHAO', 'department_id' => '19'],
            ['id' => '19701', 'name' => 'SANTA ROSA', 'department_id' => '19'],
            ['id' => '19743', 'name' => 'SILVIA', 'department_id' => '19'],
            ['id' => '19760', 'name' => 'SOTARA', 'department_id' => '19'],
            ['id' => '19780', 'name' => 'SUAREZ', 'department_id' => '19'],
            ['id' => '19785', 'name' => 'SUCRE', 'department_id' => '19'],
            ['id' => '19807', 'name' => 'TIMBIO', 'department_id' => '19'],
            ['id' => '19809', 'name' => 'TIMBIQUI', 'department_id' => '19'],
            ['id' => '19821', 'name' => 'TORIBIO', 'department_id' => '19'],
            ['id' => '19824', 'name' => 'TOTORO', 'department_id' => '19'],
            ['id' => '19845', 'name' => 'VILLA RICA', 'department_id' => '19'],
            ['id' => '20001', 'name' => 'VALLEDUPAR', 'department_id' => '20'],
            ['id' => '20011', 'name' => 'AGUACHICA', 'department_id' => '20'],
            ['id' => '20013', 'name' => 'AGUSTIN CODAZZI', 'department_id' => '20'],
            ['id' => '20032', 'name' => 'ASTREA', 'department_id' => '20'],
            ['id' => '20045', 'name' => 'BECERRIL', 'department_id' => '20'],
            ['id' => '20060', 'name' => 'BOSCONIA', 'department_id' => '20'],
            ['id' => '20175', 'name' => 'CHIMICHAGUA', 'department_id' => '20'],
            ['id' => '20178', 'name' => 'CHIRIGUANA', 'department_id' => '20'],
            ['id' => '20228', 'name' => 'CURUMANI', 'department_id' => '20'],
            ['id' => '20238', 'name' => 'EL COPEY', 'department_id' => '20'],
            ['id' => '20250', 'name' => 'EL PASO', 'department_id' => '20'],
            ['id' => '20295', 'name' => 'GAMARRA', 'department_id' => '20'],
            ['id' => '20310', 'name' => 'GONZALEZ', 'department_id' => '20'],
            ['id' => '20383', 'name' => 'LA GLORIA', 'department_id' => '20'],
            ['id' => '20400', 'name' => 'LA JAGUA DE IBIRICO', 'department_id' => '20'],
            ['id' => '20443', 'name' => 'MANAURE', 'department_id' => '20'],
            ['id' => '20517', 'name' => 'PAILITAS', 'department_id' => '20'],
            ['id' => '20550', 'name' => 'PELAYA', 'department_id' => '20'],
            ['id' => '20570', 'name' => 'PUEBLO BELLO', 'department_id' => '20'],
            ['id' => '20614', 'name' => 'RIO DE ORO', 'department_id' => '20'],
            ['id' => '20621', 'name' => 'LA PAZ', 'department_id' => '20'],
            ['id' => '20710', 'name' => 'SAN ALBERTO', 'department_id' => '20'],
            ['id' => '20750', 'name' => 'SAN DIEGO', 'department_id' => '20'],
            ['id' => '20770', 'name' => 'SAN MARTIN', 'department_id' => '20'],
            ['id' => '20787', 'name' => 'TAMALAMEQUE', 'department_id' => '20'],
            ['id' => '23001', 'name' => 'MONTERIA', 'department_id' => '23'],
            ['id' => '23068', 'name' => 'AYAPEL', 'department_id' => '23'],
            ['id' => '23079', 'name' => 'BUENAVISTA', 'department_id' => '23'],
            ['id' => '23090', 'name' => 'CANALETE', 'department_id' => '23'],
            ['id' => '23162', 'name' => 'CERETE', 'department_id' => '23'],
            ['id' => '23168', 'name' => 'CHIMA', 'department_id' => '23'],
            ['id' => '23182', 'name' => 'CHINU', 'department_id' => '23'],
            ['id' => '23189', 'name' => 'CIENAGA DE ORO', 'department_id' => '23'],
            ['id' => '23300', 'name' => 'COTORRA', 'department_id' => '23'],
            ['id' => '23350', 'name' => 'LA APARTADA', 'department_id' => '23'],
            ['id' => '23417', 'name' => 'LORICA', 'department_id' => '23'],
            ['id' => '23419', 'name' => 'LOS CORDOBAS', 'department_id' => '23'],
            ['id' => '23464', 'name' => 'MOMIL', 'department_id' => '23'],
            ['id' => '23466', 'name' => 'MONTELIBANO', 'department_id' => '23'],
            ['id' => '23500', 'name' => 'MOÑITOS', 'department_id' => '23'],
            ['id' => '23555', 'name' => 'PLANETA RICA', 'department_id' => '23'],
            ['id' => '23570', 'name' => 'PUEBLO NUEVO', 'department_id' => '23'],
            ['id' => '23574', 'name' => 'PUERTO ESCONDIDO', 'department_id' => '23'],
            ['id' => '23580', 'name' => 'PUERTO LIBERTADOR', 'department_id' => '23'],
            ['id' => '23586', 'name' => 'PURISIMA', 'department_id' => '23'],
            ['id' => '23660', 'name' => 'SAHAGUN', 'department_id' => '23'],
            ['id' => '23670', 'name' => 'SAN ANDRES SOTAVENTO', 'department_id' => '23'],
            ['id' => '23672', 'name' => 'SAN ANTERO', 'department_id' => '23'],
            ['id' => '23675', 'name' => 'SAN BERNARDO DEL VIENTO', 'department_id' => '23'],
            ['id' => '23678', 'name' => 'SAN CARLOS', 'department_id' => '23'],
            ['id' => '23686', 'name' => 'SAN PELAYO', 'department_id' => '23'],
            ['id' => '23807', 'name' => 'TIERRALTA', 'department_id' => '23'],
            ['id' => '23855', 'name' => 'VALENCIA', 'department_id' => '23'],
            ['id' => '25001', 'name' => 'AGUA DE DIOS', 'department_id' => '25'],
            ['id' => '25019', 'name' => 'ALBAN', 'department_id' => '25'],
            ['id' => '25035', 'name' => 'ANAPOIMA', 'department_id' => '25'],
            ['id' => '25040', 'name' => 'ANOLAIMA', 'department_id' => '25'],
            ['id' => '25053', 'name' => 'ARBELAEZ', 'department_id' => '25'],
            ['id' => '25086', 'name' => 'BELTRAN', 'department_id' => '25'],
            ['id' => '25095', 'name' => 'BITUIMA', 'department_id' => '25'],
            ['id' => '25099', 'name' => 'BOJACA', 'department_id' => '25'],
            ['id' => '25120', 'name' => 'CABRERA', 'department_id' => '25'],
            ['id' => '25123', 'name' => 'CACHIPAY', 'department_id' => '25'],
            ['id' => '25126', 'name' => 'CAJICA', 'department_id' => '25'],
            ['id' => '25148', 'name' => 'CAPARRAPI', 'department_id' => '25'],
            ['id' => '25151', 'name' => 'CAQUEZA', 'department_id' => '25'],
            ['id' => '25154', 'name' => 'CARMEN DE CARUPA', 'department_id' => '25'],
            ['id' => '25168', 'name' => 'CHAGUANI', 'department_id' => '25'],
            ['id' => '25175', 'name' => 'CHIA', 'department_id' => '25'],
            ['id' => '25178', 'name' => 'CHIPAQUE', 'department_id' => '25'],
            ['id' => '25181', 'name' => 'CHOACHI', 'department_id' => '25'],
            ['id' => '25183', 'name' => 'CHOCONTA', 'department_id' => '25'],
            ['id' => '25200', 'name' => 'COGUA', 'department_id' => '25'],
            ['id' => '25214', 'name' => 'COTA', 'department_id' => '25'],
            ['id' => '25224', 'name' => 'CUCUNUBA', 'department_id' => '25'],
            ['id' => '25245', 'name' => 'EL COLEGIO', 'department_id' => '25'],
            ['id' => '25258', 'name' => 'EL PEÑON', 'department_id' => '25'],
            ['id' => '25260', 'name' => 'EL ROSAL', 'department_id' => '25'],
            ['id' => '25269', 'name' => 'FACATATIVA', 'department_id' => '25'],
            ['id' => '25279', 'name' => 'FOMEQUE', 'department_id' => '25'],
            ['id' => '25281', 'name' => 'FOSCA', 'department_id' => '25'],
            ['id' => '25286', 'name' => 'FUNZA', 'department_id' => '25'],
            ['id' => '25288', 'name' => 'FUQUENE', 'department_id' => '25'],
            ['id' => '25290', 'name' => 'FUSAGASUGA', 'department_id' => '25'],
            ['id' => '25293', 'name' => 'GACHALA', 'department_id' => '25'],
            ['id' => '25295', 'name' => 'GACHANCIPA', 'department_id' => '25'],
            ['id' => '25297', 'name' => 'GACHETA', 'department_id' => '25'],
            ['id' => '25299', 'name' => 'GAMA', 'department_id' => '25'],
            ['id' => '25307', 'name' => 'GIRARDOT', 'department_id' => '25'],
            ['id' => '25312', 'name' => 'GRANADA', 'department_id' => '25'],
            ['id' => '25317', 'name' => 'GUACHETA', 'department_id' => '25'],
            ['id' => '25320', 'name' => 'GUADUAS', 'department_id' => '25'],
            ['id' => '25322', 'name' => 'GUASCA', 'department_id' => '25'],
            ['id' => '25324', 'name' => 'GUATAQUI', 'department_id' => '25'],
            ['id' => '25326', 'name' => 'GUATAVITA', 'department_id' => '25'],
            ['id' => '25328', 'name' => 'GUAYABAL DE SIQUIMA', 'department_id' => '25'],
            ['id' => '25335', 'name' => 'GUAYABETAL', 'department_id' => '25'],
            ['id' => '25339', 'name' => 'GUTIERREZ', 'department_id' => '25'],
            ['id' => '25368', 'name' => 'JERUSALEN', 'department_id' => '25'],
            ['id' => '25372', 'name' => 'JUNIN', 'department_id' => '25'],
            ['id' => '25377', 'name' => 'LA CALERA', 'department_id' => '25'],
            ['id' => '25386', 'name' => 'LA MESA', 'department_id' => '25'],
            ['id' => '25394', 'name' => 'LA PALMA', 'department_id' => '25'],
            ['id' => '25398', 'name' => 'LA PEÑA', 'department_id' => '25'],
            ['id' => '25402', 'name' => 'LA VEGA', 'department_id' => '25'],
            ['id' => '25407', 'name' => 'LENGUAZAQUE', 'department_id' => '25'],
            ['id' => '25426', 'name' => 'MACHETA', 'department_id' => '25'],
            ['id' => '25430', 'name' => 'MADRID', 'department_id' => '25'],
            ['id' => '25436', 'name' => 'MANTA', 'department_id' => '25'],
            ['id' => '25438', 'name' => 'MEDINA', 'department_id' => '25'],
            ['id' => '25473', 'name' => 'MOSQUERA', 'department_id' => '25'],
            ['id' => '25483', 'name' => 'NARIÑO', 'department_id' => '25'],
            ['id' => '25486', 'name' => 'NEMOCON', 'department_id' => '25'],
            ['id' => '25488', 'name' => 'NILO', 'department_id' => '25'],
            ['id' => '25489', 'name' => 'NIMAIMA', 'department_id' => '25'],
            ['id' => '25491', 'name' => 'NOCAIMA', 'department_id' => '25'],
            ['id' => '25506', 'name' => 'VENECIA', 'department_id' => '25'],
            ['id' => '25513', 'name' => 'PACHO', 'department_id' => '25'],
            ['id' => '25518', 'name' => 'PAIME', 'department_id' => '25'],
            ['id' => '25524', 'name' => 'PANDI', 'department_id' => '25'],
            ['id' => '25530', 'name' => 'PARATEBUENO', 'department_id' => '25'],
            ['id' => '25535', 'name' => 'PASCA', 'department_id' => '25'],
            ['id' => '25572', 'name' => 'PUERTO SALGAR', 'department_id' => '25'],
            ['id' => '25580', 'name' => 'PULI', 'department_id' => '25'],
            ['id' => '25592', 'name' => 'QUEBRADANEGRA', 'department_id' => '25'],
            ['id' => '25594', 'name' => 'QUETAME', 'department_id' => '25'],
            ['id' => '25596', 'name' => 'QUIPILE', 'department_id' => '25'],
            ['id' => '25599', 'name' => 'APULO', 'department_id' => '25'],
            ['id' => '25612', 'name' => 'RICAURTE', 'department_id' => '25'],
            ['id' => '25645', 'name' => 'SAN ANTONIO DEL TEQUENDAMA', 'department_id' => '25'],
            ['id' => '25649', 'name' => 'SAN BERNARDO', 'department_id' => '25'],
            ['id' => '25653', 'name' => 'SAN CAYETANO', 'department_id' => '25'],
            ['id' => '25658', 'name' => 'SAN FRANCISCO', 'department_id' => '25'],
            ['id' => '25662', 'name' => 'SAN JUAN DE RIO SECO', 'department_id' => '25'],
            ['id' => '25718', 'name' => 'SASAIMA', 'department_id' => '25'],
            ['id' => '25736', 'name' => 'SESQUILE', 'department_id' => '25'],
            ['id' => '25740', 'name' => 'SIBATE', 'department_id' => '25'],
            ['id' => '25743', 'name' => 'SILVANIA', 'department_id' => '25'],
            ['id' => '25745', 'name' => 'SIMIJACA', 'department_id' => '25'],
            ['id' => '25754', 'name' => 'SOACHA', 'department_id' => '25'],
            ['id' => '25758', 'name' => 'SOPO', 'department_id' => '25'],
            ['id' => '25769', 'name' => 'SUBACHOQUE', 'department_id' => '25'],
            ['id' => '25772', 'name' => 'SUESCA', 'department_id' => '25'],
            ['id' => '25777', 'name' => 'SUPATA', 'department_id' => '25'],
            ['id' => '25779', 'name' => 'SUSA', 'department_id' => '25'],
            ['id' => '25781', 'name' => 'SUTATAUSA', 'department_id' => '25'],
            ['id' => '25785', 'name' => 'TABIO', 'department_id' => '25'],
            ['id' => '25793', 'name' => 'TAUSA', 'department_id' => '25'],
            ['id' => '25797', 'name' => 'TENA', 'department_id' => '25'],
            ['id' => '25799', 'name' => 'TENJO', 'department_id' => '25'],
            ['id' => '25805', 'name' => 'TIBACUY', 'department_id' => '25'],
            ['id' => '25807', 'name' => 'TIBIRITA', 'department_id' => '25'],
            ['id' => '25815', 'name' => 'TOCAIMA', 'department_id' => '25'],
            ['id' => '25817', 'name' => 'TOCANCIPA', 'department_id' => '25'],
            ['id' => '25823', 'name' => 'TOPAIPI', 'department_id' => '25'],
            ['id' => '25839', 'name' => 'UBALA', 'department_id' => '25'],
            ['id' => '25841', 'name' => 'UBAQUE', 'department_id' => '25'],
            ['id' => '25843', 'name' => 'VILLA DE SAN DIEGO DE UBATE', 'department_id' => '25'],
            ['id' => '25845', 'name' => 'UNE', 'department_id' => '25'],
            ['id' => '25851', 'name' => 'UTICA', 'department_id' => '25'],
            ['id' => '25862', 'name' => 'VERGARA', 'department_id' => '25'],
            ['id' => '25867', 'name' => 'VIANI', 'department_id' => '25'],
            ['id' => '25871', 'name' => 'VILLAGOMEZ', 'department_id' => '25'],
            ['id' => '25873', 'name' => 'VILLAPINZON', 'department_id' => '25'],
            ['id' => '25875', 'name' => 'VILLETA', 'department_id' => '25'],
            ['id' => '25878', 'name' => 'VIOTA', 'department_id' => '25'],
            ['id' => '25885', 'name' => 'YACOPI', 'department_id' => '25'],
            ['id' => '25898', 'name' => 'ZIPACON', 'department_id' => '25'],
            ['id' => '25899', 'name' => 'ZIPAQUIRA', 'department_id' => '25'],
            ['id' => '27001', 'name' => 'QUIBDO', 'department_id' => '27'],
            ['id' => '27006', 'name' => 'ACANDI', 'department_id' => '27'],
            ['id' => '27025', 'name' => 'ALTO BAUDO', 'department_id' => '27'],
            ['id' => '27050', 'name' => 'ATRATO', 'department_id' => '27'],
            ['id' => '27073', 'name' => 'BAGADO', 'department_id' => '27'],
            ['id' => '27075', 'name' => 'BAHIA SOLANO', 'department_id' => '27'],
            ['id' => '27077', 'name' => 'BAJO BAUDO', 'department_id' => '27'],
            ['id' => '27099', 'name' => 'BOJAYA', 'department_id' => '27'],
            ['id' => '27135', 'name' => 'EL CANTON DEL SAN PABLO', 'department_id' => '27'],
            ['id' => '27150', 'name' => 'CARMEN DEL DARIEN', 'department_id' => '27'],
            ['id' => '27160', 'name' => 'CERTEGUI', 'department_id' => '27'],
            ['id' => '27205', 'name' => 'CONDOTO', 'department_id' => '27'],
            ['id' => '27245', 'name' => 'EL CARMEN DE ATRATO', 'department_id' => '27'],
            ['id' => '27250', 'name' => 'EL LITORAL DEL SAN JUAN', 'department_id' => '27'],
            ['id' => '27361', 'name' => 'ISTMINA', 'department_id' => '27'],
            ['id' => '27372', 'name' => 'JURADO', 'department_id' => '27'],
            ['id' => '27413', 'name' => 'LLORO', 'department_id' => '27'],
            ['id' => '27425', 'name' => 'MEDIO ATRATO', 'department_id' => '27'],
            ['id' => '27430', 'name' => 'MEDIO BAUDO', 'department_id' => '27'],
            ['id' => '27450', 'name' => 'MEDIO SAN JUAN', 'department_id' => '27'],
            ['id' => '27491', 'name' => 'NOVITA', 'department_id' => '27'],
            ['id' => '27495', 'name' => 'NUQUI', 'department_id' => '27'],
            ['id' => '27580', 'name' => 'RIO IRO', 'department_id' => '27'],
            ['id' => '27600', 'name' => 'RIO QUITO', 'department_id' => '27'],
            ['id' => '27615', 'name' => 'RIOSUCIO', 'department_id' => '27'],
            ['id' => '27660', 'name' => 'SAN JOSE DEL PALMAR', 'department_id' => '27'],
            ['id' => '27745', 'name' => 'SIPI', 'department_id' => '27'],
            ['id' => '27787', 'name' => 'TADO', 'department_id' => '27'],
            ['id' => '27800', 'name' => 'UNGUIA', 'department_id' => '27'],
            ['id' => '27810', 'name' => 'UNION PANAMERICANA', 'department_id' => '27'],
            ['id' => '41001', 'name' => 'NEIVA', 'department_id' => '41'],
            ['id' => '41006', 'name' => 'ACEVEDO', 'department_id' => '41'],
            ['id' => '41013', 'name' => 'AGRADO', 'department_id' => '41'],
            ['id' => '41016', 'name' => 'AIPE', 'department_id' => '41'],
            ['id' => '41020', 'name' => 'ALGECIRAS', 'department_id' => '41'],
            ['id' => '41026', 'name' => 'ALTAMIRA', 'department_id' => '41'],
            ['id' => '41078', 'name' => 'BARAYA', 'department_id' => '41'],
            ['id' => '41132', 'name' => 'CAMPOALEGRE', 'department_id' => '41'],
            ['id' => '41206', 'name' => 'COLOMBIA', 'department_id' => '41'],
            ['id' => '41244', 'name' => 'ELIAS', 'department_id' => '41'],
            ['id' => '41298', 'name' => 'GARZON', 'department_id' => '41'],
            ['id' => '41306', 'name' => 'GIGANTE', 'department_id' => '41'],
            ['id' => '41319', 'name' => 'GUADALUPE', 'department_id' => '41'],
            ['id' => '41349', 'name' => 'HOBO', 'department_id' => '41'],
            ['id' => '41357', 'name' => 'IQUIRA', 'department_id' => '41'],
            ['id' => '41359', 'name' => 'ISNOS', 'department_id' => '41'],
            ['id' => '41378', 'name' => 'LA ARGENTINA', 'department_id' => '41'],
            ['id' => '41396', 'name' => 'LA PLATA', 'department_id' => '41'],
            ['id' => '41483', 'name' => 'NATAGA', 'department_id' => '41'],
            ['id' => '41503', 'name' => 'OPORAPA', 'department_id' => '41'],
            ['id' => '41518', 'name' => 'PAICOL', 'department_id' => '41'],
            ['id' => '41524', 'name' => 'PALERMO', 'department_id' => '41'],
            ['id' => '41530', 'name' => 'PALESTINA', 'department_id' => '41'],
            ['id' => '41548', 'name' => 'PITAL', 'department_id' => '41'],
            ['id' => '41551', 'name' => 'PITALITO', 'department_id' => '41'],
            ['id' => '41615', 'name' => 'RIVERA', 'department_id' => '41'],
            ['id' => '41660', 'name' => 'SALADOBLANCO', 'department_id' => '41'],
            ['id' => '41668', 'name' => 'SAN AGUSTIN', 'department_id' => '41'],
            ['id' => '41676', 'name' => 'SANTA MARIA', 'department_id' => '41'],
            ['id' => '41770', 'name' => 'SUAZA', 'department_id' => '41'],
            ['id' => '41791', 'name' => 'TARQUI', 'department_id' => '41'],
            ['id' => '41797', 'name' => 'TESALIA', 'department_id' => '41'],
            ['id' => '41799', 'name' => 'TELLO', 'department_id' => '41'],
            ['id' => '41801', 'name' => 'TERUEL', 'department_id' => '41'],
            ['id' => '41807', 'name' => 'TIMANA', 'department_id' => '41'],
            ['id' => '41872', 'name' => 'VILLAVIEJA', 'department_id' => '41'],
            ['id' => '41885', 'name' => 'YAGUARA', 'department_id' => '41'],
            ['id' => '44001', 'name' => 'RIOHACHA', 'department_id' => '44'],
            ['id' => '44035', 'name' => 'ALBANIA', 'department_id' => '44'],
            ['id' => '44078', 'name' => 'BARRANCAS', 'department_id' => '44'],
            ['id' => '44090', 'name' => 'DIBULLA', 'department_id' => '44'],
            ['id' => '44098', 'name' => 'DISTRACCION', 'department_id' => '44'],
            ['id' => '44110', 'name' => 'EL MOLINO', 'department_id' => '44'],
            ['id' => '44279', 'name' => 'FONSECA', 'department_id' => '44'],
            ['id' => '44378', 'name' => 'HATONUEVO', 'department_id' => '44'],
            ['id' => '44420', 'name' => 'LA JAGUA DEL PILAR', 'department_id' => '44'],
            ['id' => '44430', 'name' => 'MAICAO', 'department_id' => '44'],
            ['id' => '44560', 'name' => 'MANAURE', 'department_id' => '44'],
            ['id' => '44650', 'name' => 'SAN JUAN DEL CESAR', 'department_id' => '44'],
            ['id' => '44847', 'name' => 'URIBIA', 'department_id' => '44'],
            ['id' => '44855', 'name' => 'URUMITA', 'department_id' => '44'],
            ['id' => '44874', 'name' => 'VILLANUEVA', 'department_id' => '44'],
            ['id' => '47001', 'name' => 'SANTA MARTA', 'department_id' => '47'],
            ['id' => '47030', 'name' => 'ALGARROBO', 'department_id' => '47'],
            ['id' => '47053', 'name' => 'ARACATACA', 'department_id' => '47'],
            ['id' => '47058', 'name' => 'ARIGUANI', 'department_id' => '47'],
            ['id' => '47161', 'name' => 'CERRO SAN ANTONIO', 'department_id' => '47'],
            ['id' => '47170', 'name' => 'CHIBOLO', 'department_id' => '47'],
            ['id' => '47189', 'name' => 'CIENAGA', 'department_id' => '47'],
            ['id' => '47205', 'name' => 'CONCORDIA', 'department_id' => '47'],
            ['id' => '47245', 'name' => 'EL BANCO', 'department_id' => '47'],
            ['id' => '47258', 'name' => 'EL PIÑON', 'department_id' => '47'],
            ['id' => '47268', 'name' => 'EL RETEN', 'department_id' => '47'],
            ['id' => '47288', 'name' => 'FUNDACION', 'department_id' => '47'],
            ['id' => '47318', 'name' => 'GUAMAL', 'department_id' => '47'],
            ['id' => '47460', 'name' => 'NUEVA GRANADA', 'department_id' => '47'],
            ['id' => '47541', 'name' => 'PEDRAZA', 'department_id' => '47'],
            ['id' => '47545', 'name' => 'PIJIÑO DEL CARMEN', 'department_id' => '47'],
            ['id' => '47551', 'name' => 'PIVIJAY', 'department_id' => '47'],
            ['id' => '47555', 'name' => 'PLATO', 'department_id' => '47'],
            ['id' => '47570', 'name' => 'PUEBLOVIEJO', 'department_id' => '47'],
            ['id' => '47605', 'name' => 'REMOLINO', 'department_id' => '47'],
            ['id' => '47660', 'name' => 'SABANAS DE SAN ANGEL', 'department_id' => '47'],
            ['id' => '47675', 'name' => 'SALAMINA', 'department_id' => '47'],
            ['id' => '47692', 'name' => 'SAN SEBASTIAN DE BUENAVISTA', 'department_id' => '47'],
            ['id' => '47703', 'name' => 'SAN ZENON', 'department_id' => '47'],
            ['id' => '47707', 'name' => 'SANTA ANA', 'department_id' => '47'],
            ['id' => '47720', 'name' => 'SANTA BARBARA DE PINTO', 'department_id' => '47'],
            ['id' => '47745', 'name' => 'SITIONUEVO', 'department_id' => '47'],
            ['id' => '47798', 'name' => 'TENERIFE', 'department_id' => '47'],
            ['id' => '47960', 'name' => 'ZAPAYAN', 'department_id' => '47'],
            ['id' => '47980', 'name' => 'ZONA BANANERA', 'department_id' => '47'],
            ['id' => '50001', 'name' => 'VILLAVICENCIO', 'department_id' => '50'],
            ['id' => '50006', 'name' => 'ACACIAS', 'department_id' => '50'],
            ['id' => '50110', 'name' => 'BARRANCA DE UPIA', 'department_id' => '50'],
            ['id' => '50124', 'name' => 'CABUYARO', 'department_id' => '50'],
            ['id' => '50150', 'name' => 'CASTILLA LA NUEVA', 'department_id' => '50'],
            ['id' => '50223', 'name' => 'CUBARRAL', 'department_id' => '50'],
            ['id' => '50226', 'name' => 'CUMARAL', 'department_id' => '50'],
            ['id' => '50245', 'name' => 'EL CALVARIO', 'department_id' => '50'],
            ['id' => '50251', 'name' => 'EL CASTILLO', 'department_id' => '50'],
            ['id' => '50270', 'name' => 'EL DORADO', 'department_id' => '50'],
            ['id' => '50287', 'name' => 'FUENTE DE ORO', 'department_id' => '50'],
            ['id' => '50313', 'name' => 'GRANADA', 'department_id' => '50'],
            ['id' => '50318', 'name' => 'GUAMAL', 'department_id' => '50'],
            ['id' => '50325', 'name' => 'MAPIRIPAN', 'department_id' => '50'],
            ['id' => '50330', 'name' => 'MESETAS', 'department_id' => '50'],
            ['id' => '50350', 'name' => 'LA MACARENA', 'department_id' => '50'],
            ['id' => '50370', 'name' => 'URIBE', 'department_id' => '50'],
            ['id' => '50400', 'name' => 'LEJANIAS', 'department_id' => '50'],
            ['id' => '50450', 'name' => 'PUERTO CONCORDIA', 'department_id' => '50'],
            ['id' => '50568', 'name' => 'PUERTO GAITAN', 'department_id' => '50'],
            ['id' => '50573', 'name' => 'PUERTO LOPEZ', 'department_id' => '50'],
            ['id' => '50577', 'name' => 'PUERTO LLERAS', 'department_id' => '50'],
            ['id' => '50590', 'name' => 'PUERTO RICO', 'department_id' => '50'],
            ['id' => '50606', 'name' => 'RESTREPO', 'department_id' => '50'],
            ['id' => '50680', 'name' => 'SAN CARLOS DE GUAROA', 'department_id' => '50'],
            ['id' => '50683', 'name' => 'SAN JUAN DE ARAMA', 'department_id' => '50'],
            ['id' => '50686', 'name' => 'SAN JUANITO', 'department_id' => '50'],
            ['id' => '50689', 'name' => 'SAN MARTIN', 'department_id' => '50'],
            ['id' => '50711', 'name' => 'VISTAHERMOSA', 'department_id' => '50'],
            ['id' => '52001', 'name' => 'PASTO', 'department_id' => '52'],
            ['id' => '52019', 'name' => 'ALBAN', 'department_id' => '52'],
            ['id' => '52022', 'name' => 'ALDANA', 'department_id' => '52'],
            ['id' => '52036', 'name' => 'ANCUYA', 'department_id' => '52'],
            ['id' => '52051', 'name' => 'ARBOLEDA', 'department_id' => '52'],
            ['id' => '52079', 'name' => 'BARBACOAS', 'department_id' => '52'],
            ['id' => '52083', 'name' => 'BELEN', 'department_id' => '52'],
            ['id' => '52110', 'name' => 'BUESACO', 'department_id' => '52'],
            ['id' => '52203', 'name' => 'COLON', 'department_id' => '52'],
            ['id' => '52207', 'name' => 'CONSACA', 'department_id' => '52'],
            ['id' => '52210', 'name' => 'CONTADERO', 'department_id' => '52'],
            ['id' => '52215', 'name' => 'CORDOBA', 'department_id' => '52'],
            ['id' => '52224', 'name' => 'CUASPUD', 'department_id' => '52'],
            ['id' => '52227', 'name' => 'CUMBAL', 'department_id' => '52'],
            ['id' => '52233', 'name' => 'CUMBITARA', 'department_id' => '52'],
            ['id' => '52240', 'name' => 'CHACHAGsI', 'department_id' => '52'],
            ['id' => '52250', 'name' => 'EL CHARCO', 'department_id' => '52'],
            ['id' => '52254', 'name' => 'EL PEÑOL', 'department_id' => '52'],
            ['id' => '52256', 'name' => 'EL ROSARIO', 'department_id' => '52'],
            ['id' => '52258', 'name' => 'EL TABLON DE GOMEZ', 'department_id' => '52'],
            ['id' => '52260', 'name' => 'EL TAMBO', 'department_id' => '52'],
            ['id' => '52287', 'name' => 'FUNES', 'department_id' => '52'],
            ['id' => '52317', 'name' => 'GUACHUCAL', 'department_id' => '52'],
            ['id' => '52320', 'name' => 'GUAITARILLA', 'department_id' => '52'],
            ['id' => '52323', 'name' => 'GUALMATAN', 'department_id' => '52'],
            ['id' => '52352', 'name' => 'ILES', 'department_id' => '52'],
            ['id' => '52354', 'name' => 'IMUES', 'department_id' => '52'],
            ['id' => '52356', 'name' => 'IPIALES', 'department_id' => '52'],
            ['id' => '52378', 'name' => 'LA CRUZ', 'department_id' => '52'],
            ['id' => '52381', 'name' => 'LA FLORIDA', 'department_id' => '52'],
            ['id' => '52385', 'name' => 'LA LLANADA', 'department_id' => '52'],
            ['id' => '52390', 'name' => 'LA TOLA', 'department_id' => '52'],
            ['id' => '52399', 'name' => 'LA UNION', 'department_id' => '52'],
            ['id' => '52405', 'name' => 'LEIVA', 'department_id' => '52'],
            ['id' => '52411', 'name' => 'LINARES', 'department_id' => '52'],
            ['id' => '52418', 'name' => 'LOS ANDES', 'department_id' => '52'],
            ['id' => '52427', 'name' => 'MAGsI', 'department_id' => '52'],
            ['id' => '52435', 'name' => 'MALLAMA', 'department_id' => '52'],
            ['id' => '52473', 'name' => 'MOSQUERA', 'department_id' => '52'],
            ['id' => '52480', 'name' => 'NARIÑO', 'department_id' => '52'],
            ['id' => '52490', 'name' => 'OLAYA HERRERA', 'department_id' => '52'],
            ['id' => '52506', 'name' => 'OSPINA', 'department_id' => '52'],
            ['id' => '52520', 'name' => 'FRANCISCO PIZARRO', 'department_id' => '52'],
            ['id' => '52540', 'name' => 'POLICARPA', 'department_id' => '52'],
            ['id' => '52560', 'name' => 'POTOSI', 'department_id' => '52'],
            ['id' => '52565', 'name' => 'PROVIDENCIA', 'department_id' => '52'],
            ['id' => '52573', 'name' => 'PUERRES', 'department_id' => '52'],
            ['id' => '52585', 'name' => 'PUPIALES', 'department_id' => '52'],
            ['id' => '52612', 'name' => 'RICAURTE', 'department_id' => '52'],
            ['id' => '52621', 'name' => 'ROBERTO PAYAN', 'department_id' => '52'],
            ['id' => '52678', 'name' => 'SAMANIEGO', 'department_id' => '52'],
            ['id' => '52683', 'name' => 'SANDONA', 'department_id' => '52'],
            ['id' => '52685', 'name' => 'SAN BERNARDO', 'department_id' => '52'],
            ['id' => '52687', 'name' => 'SAN LORENZO', 'department_id' => '52'],
            ['id' => '52693', 'name' => 'SAN PABLO', 'department_id' => '52'],
            ['id' => '52694', 'name' => 'SAN PEDRO DE CARTAGO', 'department_id' => '52'],
            ['id' => '52696', 'name' => 'SANTA BARBARA', 'department_id' => '52'],
            ['id' => '52699', 'name' => 'SANTACRUZ', 'department_id' => '52'],
            ['id' => '52720', 'name' => 'SAPUYES', 'department_id' => '52'],
            ['id' => '52786', 'name' => 'TAMINANGO', 'department_id' => '52'],
            ['id' => '52788', 'name' => 'TANGUA', 'department_id' => '52'],
            ['id' => '52835', 'name' => 'SAN ANDRES DE TUMACO', 'department_id' => '52'],
            ['id' => '52838', 'name' => 'TUQUERRES', 'department_id' => '52'],
            ['id' => '52885', 'name' => 'YACUANQUER', 'department_id' => '52'],
            ['id' => '54001', 'name' => 'CUCUTA', 'department_id' => '54'],
            ['id' => '54003', 'name' => 'ABREGO', 'department_id' => '54'],
            ['id' => '54051', 'name' => 'ARBOLEDAS', 'department_id' => '54'],
            ['id' => '54099', 'name' => 'BOCHALEMA', 'department_id' => '54'],
            ['id' => '54109', 'name' => 'BUCARASICA', 'department_id' => '54'],
            ['id' => '54125', 'name' => 'CACOTA', 'department_id' => '54'],
            ['id' => '54128', 'name' => 'CACHIRA', 'department_id' => '54'],
            ['id' => '54172', 'name' => 'CHINACOTA', 'department_id' => '54'],
            ['id' => '54174', 'name' => 'CHITAGA', 'department_id' => '54'],
            ['id' => '54206', 'name' => 'CONVENCION', 'department_id' => '54'],
            ['id' => '54223', 'name' => 'CUCUTILLA', 'department_id' => '54'],
            ['id' => '54239', 'name' => 'DURANIA', 'department_id' => '54'],
            ['id' => '54245', 'name' => 'EL CARMEN', 'department_id' => '54'],
            ['id' => '54250', 'name' => 'EL TARRA', 'department_id' => '54'],
            ['id' => '54261', 'name' => 'EL ZULIA', 'department_id' => '54'],
            ['id' => '54313', 'name' => 'GRAMALOTE', 'department_id' => '54'],
            ['id' => '54344', 'name' => 'HACARI', 'department_id' => '54'],
            ['id' => '54347', 'name' => 'HERRAN', 'department_id' => '54'],
            ['id' => '54377', 'name' => 'LABATECA', 'department_id' => '54'],
            ['id' => '54385', 'name' => 'LA ESPERANZA', 'department_id' => '54'],
            ['id' => '54398', 'name' => 'LA PLAYA', 'department_id' => '54'],
            ['id' => '54405', 'name' => 'LOS PATIOS', 'department_id' => '54'],
            ['id' => '54418', 'name' => 'LOURDES', 'department_id' => '54'],
            ['id' => '54480', 'name' => 'MUTISCUA', 'department_id' => '54'],
            ['id' => '54498', 'name' => 'OCAÑA', 'department_id' => '54'],
            ['id' => '54518', 'name' => 'PAMPLONA', 'department_id' => '54'],
            ['id' => '54520', 'name' => 'PAMPLONITA', 'department_id' => '54'],
            ['id' => '54553', 'name' => 'PUERTO SANTANDER', 'department_id' => '54'],
            ['id' => '54599', 'name' => 'RAGONVALIA', 'department_id' => '54'],
            ['id' => '54660', 'name' => 'SALAZAR', 'department_id' => '54'],
            ['id' => '54670', 'name' => 'SAN CALIXTO', 'department_id' => '54'],
            ['id' => '54673', 'name' => 'SAN CAYETANO', 'department_id' => '54'],
            ['id' => '54680', 'name' => 'SANTIAGO', 'department_id' => '54'],
            ['id' => '54720', 'name' => 'SARDINATA', 'department_id' => '54'],
            ['id' => '54743', 'name' => 'SILOS', 'department_id' => '54'],
            ['id' => '54800', 'name' => 'TEORAMA', 'department_id' => '54'],
            ['id' => '54810', 'name' => 'TIBU', 'department_id' => '54'],
            ['id' => '54820', 'name' => 'TOLEDO', 'department_id' => '54'],
            ['id' => '54871', 'name' => 'VILLA CARO', 'department_id' => '54'],
            ['id' => '54874', 'name' => 'VILLA DEL ROSARIO', 'department_id' => '54'],
            ['id' => '63001', 'name' => 'ARMENIA', 'department_id' => '63'],
            ['id' => '63111', 'name' => 'BUENAVISTA', 'department_id' => '63'],
            ['id' => '63130', 'name' => 'CALARCA', 'department_id' => '63'],
            ['id' => '63190', 'name' => 'CIRCASIA', 'department_id' => '63'],
            ['id' => '63212', 'name' => 'CORDOBA', 'department_id' => '63'],
            ['id' => '63272', 'name' => 'FILANDIA', 'department_id' => '63'],
            ['id' => '63302', 'name' => 'GENOVA', 'department_id' => '63'],
            ['id' => '63401', 'name' => 'LA TEBAIDA', 'department_id' => '63'],
            ['id' => '63470', 'name' => 'MONTENEGRO', 'department_id' => '63'],
            ['id' => '63548', 'name' => 'PIJAO', 'department_id' => '63'],
            ['id' => '63594', 'name' => 'QUIMBAYA', 'department_id' => '63'],
            ['id' => '63690', 'name' => 'SALENTO', 'department_id' => '63'],
            ['id' => '66001', 'name' => 'PEREIRA', 'department_id' => '66'],
            ['id' => '66045', 'name' => 'APIA', 'department_id' => '66'],
            ['id' => '66075', 'name' => 'BALBOA', 'department_id' => '66'],
            ['id' => '66088', 'name' => 'BELEN DE UMBRIA', 'department_id' => '66'],
            ['id' => '66170', 'name' => 'DOSQUEBRADAS', 'department_id' => '66'],
            ['id' => '66318', 'name' => 'GUATICA', 'department_id' => '66'],
            ['id' => '66383', 'name' => 'LA CELIA', 'department_id' => '66'],
            ['id' => '66400', 'name' => 'LA VIRGINIA', 'department_id' => '66'],
            ['id' => '66440', 'name' => 'MARSELLA', 'department_id' => '66'],
            ['id' => '66456', 'name' => 'MISTRATO', 'department_id' => '66'],
            ['id' => '66572', 'name' => 'PUEBLO RICO', 'department_id' => '66'],
            ['id' => '66594', 'name' => 'QUINCHIA', 'department_id' => '66'],
            ['id' => '66682', 'name' => 'SANTA ROSA DE CABAL', 'department_id' => '66'],
            ['id' => '66687', 'name' => 'SANTUARIO', 'department_id' => '66'],
            ['id' => '68001', 'name' => 'BUCARAMANGA', 'department_id' => '68'],
            ['id' => '68013', 'name' => 'AGUADA', 'department_id' => '68'],
            ['id' => '68020', 'name' => 'ALBANIA', 'department_id' => '68'],
            ['id' => '68051', 'name' => 'ARATOCA', 'department_id' => '68'],
            ['id' => '68077', 'name' => 'BARBOSA', 'department_id' => '68'],
            ['id' => '68079', 'name' => 'BARICHARA', 'department_id' => '68'],
            ['id' => '68081', 'name' => 'BARRANCABERMEJA', 'department_id' => '68'],
            ['id' => '68092', 'name' => 'BETULIA', 'department_id' => '68'],
            ['id' => '68101', 'name' => 'BOLIVAR', 'department_id' => '68'],
            ['id' => '68121', 'name' => 'CABRERA', 'department_id' => '68'],
            ['id' => '68132', 'name' => 'CALIFORNIA', 'department_id' => '68'],
            ['id' => '68147', 'name' => 'CAPITANEJO', 'department_id' => '68'],
            ['id' => '68152', 'name' => 'CARCASI', 'department_id' => '68'],
            ['id' => '68160', 'name' => 'CEPITA', 'department_id' => '68'],
            ['id' => '68162', 'name' => 'CERRITO', 'department_id' => '68'],
            ['id' => '68167', 'name' => 'CHARALA', 'department_id' => '68'],
            ['id' => '68169', 'name' => 'CHARTA', 'department_id' => '68'],
            ['id' => '68176', 'name' => 'CHIMA', 'department_id' => '68'],
            ['id' => '68179', 'name' => 'CHIPATA', 'department_id' => '68'],
            ['id' => '68190', 'name' => 'CIMITARRA', 'department_id' => '68'],
            ['id' => '68207', 'name' => 'CONCEPCION', 'department_id' => '68'],
            ['id' => '68209', 'name' => 'CONFINES', 'department_id' => '68'],
            ['id' => '68211', 'name' => 'CONTRATACION', 'department_id' => '68'],
            ['id' => '68217', 'name' => 'COROMORO', 'department_id' => '68'],
            ['id' => '68229', 'name' => 'CURITI', 'department_id' => '68'],
            ['id' => '68235', 'name' => 'EL CARMEN DE CHUCURI', 'department_id' => '68'],
            ['id' => '68245', 'name' => 'EL GUACAMAYO', 'department_id' => '68'],
            ['id' => '68250', 'name' => 'EL PEÑON', 'department_id' => '68'],
            ['id' => '68255', 'name' => 'EL PLAYON', 'department_id' => '68'],
            ['id' => '68264', 'name' => 'ENCINO', 'department_id' => '68'],
            ['id' => '68266', 'name' => 'ENCISO', 'department_id' => '68'],
            ['id' => '68271', 'name' => 'FLORIAN', 'department_id' => '68'],
            ['id' => '68276', 'name' => 'FLORIDABLANCA', 'department_id' => '68'],
            ['id' => '68296', 'name' => 'GALAN', 'department_id' => '68'],
            ['id' => '68298', 'name' => 'GAMBITA', 'department_id' => '68'],
            ['id' => '68307', 'name' => 'GIRON', 'department_id' => '68'],
            ['id' => '68318', 'name' => 'GUACA', 'department_id' => '68'],
            ['id' => '68320', 'name' => 'GUADALUPE', 'department_id' => '68'],
            ['id' => '68322', 'name' => 'GUAPOTA', 'department_id' => '68'],
            ['id' => '68324', 'name' => 'GUAVATA', 'department_id' => '68'],
            ['id' => '68327', 'name' => 'GsEPSA', 'department_id' => '68'],
            ['id' => '68344', 'name' => 'HATO', 'department_id' => '68'],
            ['id' => '68368', 'name' => 'JESUS MARIA', 'department_id' => '68'],
            ['id' => '68370', 'name' => 'JORDAN', 'department_id' => '68'],
            ['id' => '68377', 'name' => 'LA BELLEZA', 'department_id' => '68'],
            ['id' => '68385', 'name' => 'LANDAZURI', 'department_id' => '68'],
            ['id' => '68397', 'name' => 'LA PAZ', 'department_id' => '68'],
            ['id' => '68406', 'name' => 'LEBRIJA', 'department_id' => '68'],
            ['id' => '68418', 'name' => 'LOS SANTOS', 'department_id' => '68'],
            ['id' => '68425', 'name' => 'MACARAVITA', 'department_id' => '68'],
            ['id' => '68432', 'name' => 'MALAGA', 'department_id' => '68'],
            ['id' => '68444', 'name' => 'MATANZA', 'department_id' => '68'],
            ['id' => '68464', 'name' => 'MOGOTES', 'department_id' => '68'],
            ['id' => '68468', 'name' => 'MOLAGAVITA', 'department_id' => '68'],
            ['id' => '68498', 'name' => 'OCAMONTE', 'department_id' => '68'],
            ['id' => '68500', 'name' => 'OIBA', 'department_id' => '68'],
            ['id' => '68502', 'name' => 'ONZAGA', 'department_id' => '68'],
            ['id' => '68522', 'name' => 'PALMAR', 'department_id' => '68'],
            ['id' => '68524', 'name' => 'PALMAS DEL SOCORRO', 'department_id' => '68'],
            ['id' => '68533', 'name' => 'PARAMO', 'department_id' => '68'],
            ['id' => '68547', 'name' => 'PIEDECUESTA', 'department_id' => '68'],
            ['id' => '68549', 'name' => 'PINCHOTE', 'department_id' => '68'],
            ['id' => '68572', 'name' => 'PUENTE NACIONAL', 'department_id' => '68'],
            ['id' => '68573', 'name' => 'PUERTO PARRA', 'department_id' => '68'],
            ['id' => '68575', 'name' => 'PUERTO WILCHES', 'department_id' => '68'],
            ['id' => '68615', 'name' => 'RIONEGRO', 'department_id' => '68'],
            ['id' => '68655', 'name' => 'SABANA DE TORRES', 'department_id' => '68'],
            ['id' => '68669', 'name' => 'SAN ANDRES', 'department_id' => '68'],
            ['id' => '68673', 'name' => 'SAN BENITO', 'department_id' => '68'],
            ['id' => '68679', 'name' => 'SAN GIL', 'department_id' => '68'],
            ['id' => '68682', 'name' => 'SAN JOAQUIN', 'department_id' => '68'],
            ['id' => '68684', 'name' => 'SAN JOSE DE MIRANDA', 'department_id' => '68'],
            ['id' => '68686', 'name' => 'SAN MIGUEL', 'department_id' => '68'],
            ['id' => '68689', 'name' => 'SAN VICENTE DE CHUCURI', 'department_id' => '68'],
            ['id' => '68705', 'name' => 'SANTA BARBARA', 'department_id' => '68'],
            ['id' => '68720', 'name' => 'SANTA HELENA DEL OPON', 'department_id' => '68'],
            ['id' => '68745', 'name' => 'SIMACOTA', 'department_id' => '68'],
            ['id' => '68755', 'name' => 'SOCORRO', 'department_id' => '68'],
            ['id' => '68770', 'name' => 'SUAITA', 'department_id' => '68'],
            ['id' => '68773', 'name' => 'SUCRE', 'department_id' => '68'],
            ['id' => '68780', 'name' => 'SURATA', 'department_id' => '68'],
            ['id' => '68820', 'name' => 'TONA', 'department_id' => '68'],
            ['id' => '68855', 'name' => 'VALLE DE SAN JOSE', 'department_id' => '68'],
            ['id' => '68861', 'name' => 'VELEZ', 'department_id' => '68'],
            ['id' => '68867', 'name' => 'VETAS', 'department_id' => '68'],
            ['id' => '68872', 'name' => 'VILLANUEVA', 'department_id' => '68'],
            ['id' => '68895', 'name' => 'ZAPATOCA', 'department_id' => '68'],
            ['id' => '70001', 'name' => 'SINCELEJO', 'department_id' => '70'],
            ['id' => '70110', 'name' => 'BUENAVISTA', 'department_id' => '70'],
            ['id' => '70124', 'name' => 'CAIMITO', 'department_id' => '70'],
            ['id' => '70204', 'name' => 'COLOSO', 'department_id' => '70'],
            ['id' => '70215', 'name' => 'COROZAL', 'department_id' => '70'],
            ['id' => '70221', 'name' => 'COVEÑAS', 'department_id' => '70'],
            ['id' => '70230', 'name' => 'CHALAN', 'department_id' => '70'],
            ['id' => '70233', 'name' => 'EL ROBLE', 'department_id' => '70'],
            ['id' => '70235', 'name' => 'GALERAS', 'department_id' => '70'],
            ['id' => '70265', 'name' => 'GUARANDA', 'department_id' => '70'],
            ['id' => '70400', 'name' => 'LA UNION', 'department_id' => '70'],
            ['id' => '70418', 'name' => 'LOS PALMITOS', 'department_id' => '70'],
            ['id' => '70429', 'name' => 'MAJAGUAL', 'department_id' => '70'],
            ['id' => '70473', 'name' => 'MORROA', 'department_id' => '70'],
            ['id' => '70508', 'name' => 'OVEJAS', 'department_id' => '70'],
            ['id' => '70523', 'name' => 'PALMITO', 'department_id' => '70'],
            ['id' => '70670', 'name' => 'SAMPUES', 'department_id' => '70'],
            ['id' => '70678', 'name' => 'SAN BENITO ABAD', 'department_id' => '70'],
            ['id' => '70702', 'name' => 'SAN JUAN DE BETULIA', 'department_id' => '70'],
            ['id' => '70708', 'name' => 'SAN MARCOS', 'department_id' => '70'],
            ['id' => '70713', 'name' => 'SAN ONOFRE', 'department_id' => '70'],
            ['id' => '70717', 'name' => 'SAN PEDRO', 'department_id' => '70'],
            ['id' => '70742', 'name' => 'SAN LUIS DE SINCE', 'department_id' => '70'],
            ['id' => '70771', 'name' => 'SUCRE', 'department_id' => '70'],
            ['id' => '70820', 'name' => 'SANTIAGO DE TOLU', 'department_id' => '70'],
            ['id' => '70823', 'name' => 'TOLU VIEJO', 'department_id' => '70'],
            ['id' => '73001', 'name' => 'IBAGUE', 'department_id' => '73'],
            ['id' => '73024', 'name' => 'ALPUJARRA', 'department_id' => '73'],
            ['id' => '73026', 'name' => 'ALVARADO', 'department_id' => '73'],
            ['id' => '73030', 'name' => 'AMBALEMA', 'department_id' => '73'],
            ['id' => '73043', 'name' => 'ANZOATEGUI', 'department_id' => '73'],
            ['id' => '73055', 'name' => 'ARMERO', 'department_id' => '73'],
            ['id' => '73067', 'name' => 'ATACO', 'department_id' => '73'],
            ['id' => '73124', 'name' => 'CAJAMARCA', 'department_id' => '73'],
            ['id' => '73148', 'name' => 'CARMEN DE APICALA', 'department_id' => '73'],
            ['id' => '73152', 'name' => 'CASABIANCA', 'department_id' => '73'],
            ['id' => '73168', 'name' => 'CHAPARRAL', 'department_id' => '73'],
            ['id' => '73200', 'name' => 'COELLO', 'department_id' => '73'],
            ['id' => '73217', 'name' => 'COYAIMA', 'department_id' => '73'],
            ['id' => '73226', 'name' => 'CUNDAY', 'department_id' => '73'],
            ['id' => '73236', 'name' => 'DOLORES', 'department_id' => '73'],
            ['id' => '73268', 'name' => 'ESPINAL', 'department_id' => '73'],
            ['id' => '73270', 'name' => 'FALAN', 'department_id' => '73'],
            ['id' => '73275', 'name' => 'FLANDES', 'department_id' => '73'],
            ['id' => '73283', 'name' => 'FRESNO', 'department_id' => '73'],
            ['id' => '73319', 'name' => 'GUAMO', 'department_id' => '73'],
            ['id' => '73347', 'name' => 'HERVEO', 'department_id' => '73'],
            ['id' => '73349', 'name' => 'HONDA', 'department_id' => '73'],
            ['id' => '73352', 'name' => 'ICONONZO', 'department_id' => '73'],
            ['id' => '73408', 'name' => 'LERIDA', 'department_id' => '73'],
            ['id' => '73411', 'name' => 'LIBANO', 'department_id' => '73'],
            ['id' => '73443', 'name' => 'MARIQUITA', 'department_id' => '73'],
            ['id' => '73449', 'name' => 'MELGAR', 'department_id' => '73'],
            ['id' => '73461', 'name' => 'MURILLO', 'department_id' => '73'],
            ['id' => '73483', 'name' => 'NATAGAIMA', 'department_id' => '73'],
            ['id' => '73504', 'name' => 'ORTEGA', 'department_id' => '73'],
            ['id' => '73520', 'name' => 'PALOCABILDO', 'department_id' => '73'],
            ['id' => '73547', 'name' => 'PIEDRAS', 'department_id' => '73'],
            ['id' => '73555', 'name' => 'PLANADAS', 'department_id' => '73'],
            ['id' => '73563', 'name' => 'PRADO', 'department_id' => '73'],
            ['id' => '73585', 'name' => 'PURIFICACION', 'department_id' => '73'],
            ['id' => '73616', 'name' => 'RIOBLANCO', 'department_id' => '73'],
            ['id' => '73622', 'name' => 'RONCESVALLES', 'department_id' => '73'],
            ['id' => '73624', 'name' => 'ROVIRA', 'department_id' => '73'],
            ['id' => '73671', 'name' => 'SALDAÑA', 'department_id' => '73'],
            ['id' => '73675', 'name' => 'SAN ANTONIO', 'department_id' => '73'],
            ['id' => '73678', 'name' => 'SAN LUIS', 'department_id' => '73'],
            ['id' => '73686', 'name' => 'SANTA ISABEL', 'department_id' => '73'],
            ['id' => '73770', 'name' => 'SUAREZ', 'department_id' => '73'],
            ['id' => '73854', 'name' => 'VALLE DE SAN JUAN', 'department_id' => '73'],
            ['id' => '73861', 'name' => 'VENADILLO', 'department_id' => '73'],
            ['id' => '73870', 'name' => 'VILLAHERMOSA', 'department_id' => '73'],
            ['id' => '73873', 'name' => 'VILLARRICA', 'department_id' => '73'],
            ['id' => '76001', 'name' => 'CALI', 'department_id' => '76'],
            ['id' => '76020', 'name' => 'ALCALA', 'department_id' => '76'],
            ['id' => '76036', 'name' => 'ANDALUCIA', 'department_id' => '76'],
            ['id' => '76041', 'name' => 'ANSERMANUEVO', 'department_id' => '76'],
            ['id' => '76054', 'name' => 'ARGELIA', 'department_id' => '76'],
            ['id' => '76100', 'name' => 'BOLIVAR', 'department_id' => '76'],
            ['id' => '76109', 'name' => 'BUENAVENTURA', 'department_id' => '76'],
            ['id' => '76111', 'name' => 'GUADALAJARA DE BUGA', 'department_id' => '76'],
            ['id' => '76113', 'name' => 'BUGALAGRANDE', 'department_id' => '76'],
            ['id' => '76122', 'name' => 'CAICEDONIA', 'department_id' => '76'],
            ['id' => '76126', 'name' => 'CALIMA', 'department_id' => '76'],
            ['id' => '76130', 'name' => 'CANDELARIA', 'department_id' => '76'],
            ['id' => '76147', 'name' => 'CARTAGO', 'department_id' => '76'],
            ['id' => '76233', 'name' => 'DAGUA', 'department_id' => '76'],
            ['id' => '76243', 'name' => 'EL AGUILA', 'department_id' => '76'],
            ['id' => '76246', 'name' => 'EL CAIRO', 'department_id' => '76'],
            ['id' => '76248', 'name' => 'EL CERRITO', 'department_id' => '76'],
            ['id' => '76250', 'name' => 'EL DOVIO', 'department_id' => '76'],
            ['id' => '76275', 'name' => 'FLORIDA', 'department_id' => '76'],
            ['id' => '76306', 'name' => 'GINEBRA', 'department_id' => '76'],
            ['id' => '76318', 'name' => 'GUACARI', 'department_id' => '76'],
            ['id' => '76364', 'name' => 'JAMUNDI', 'department_id' => '76'],
            ['id' => '76377', 'name' => 'LA CUMBRE', 'department_id' => '76'],
            ['id' => '76400', 'name' => 'LA UNION', 'department_id' => '76'],
            ['id' => '76403', 'name' => 'LA VICTORIA', 'department_id' => '76'],
            ['id' => '76497', 'name' => 'OBANDO', 'department_id' => '76'],
            ['id' => '76520', 'name' => 'PALMIRA', 'department_id' => '76'],
            ['id' => '76563', 'name' => 'PRADERA', 'department_id' => '76'],
            ['id' => '76606', 'name' => 'RESTREPO', 'department_id' => '76'],
            ['id' => '76616', 'name' => 'RIOFRIO', 'department_id' => '76'],
            ['id' => '76622', 'name' => 'ROLDANILLO', 'department_id' => '76'],
            ['id' => '76670', 'name' => 'SAN PEDRO', 'department_id' => '76'],
            ['id' => '76736', 'name' => 'SEVILLA', 'department_id' => '76'],
            ['id' => '76823', 'name' => 'TORO', 'department_id' => '76'],
            ['id' => '76828', 'name' => 'TRUJILLO', 'department_id' => '76'],
            ['id' => '76834', 'name' => 'TULUA', 'department_id' => '76'],
            ['id' => '76845', 'name' => 'ULLOA', 'department_id' => '76'],
            ['id' => '76863', 'name' => 'VERSALLES', 'department_id' => '76'],
            ['id' => '76869', 'name' => 'VIJES', 'department_id' => '76'],
            ['id' => '76890', 'name' => 'YOTOCO', 'department_id' => '76'],
            ['id' => '76892', 'name' => 'YUMBO', 'department_id' => '76'],
            ['id' => '76895', 'name' => 'ZARZAL', 'department_id' => '76'],
            ['id' => '81001', 'name' => 'ARAUCA', 'department_id' => '81'],
            ['id' => '81065', 'name' => 'ARAUQUITA', 'department_id' => '81'],
            ['id' => '81220', 'name' => 'CRAVO NORTE', 'department_id' => '81'],
            ['id' => '81300', 'name' => 'FORTUL', 'department_id' => '81'],
            ['id' => '81591', 'name' => 'PUERTO RONDON', 'department_id' => '81'],
            ['id' => '81736', 'name' => 'SARAVENA', 'department_id' => '81'],
            ['id' => '81794', 'name' => 'TAME', 'department_id' => '81'],
            ['id' => '85001', 'name' => 'YOPAL', 'department_id' => '85'],
            ['id' => '85010', 'name' => 'AGUAZUL', 'department_id' => '85'],
            ['id' => '85015', 'name' => 'CHAMEZA', 'department_id' => '85'],
            ['id' => '85125', 'name' => 'HATO COROZAL', 'department_id' => '85'],
            ['id' => '85136', 'name' => 'LA SALINA', 'department_id' => '85'],
            ['id' => '85139', 'name' => 'MANI', 'department_id' => '85'],
            ['id' => '85162', 'name' => 'MONTERREY', 'department_id' => '85'],
            ['id' => '85225', 'name' => 'NUNCHIA', 'department_id' => '85'],
            ['id' => '85230', 'name' => 'OROCUE', 'department_id' => '85'],
            ['id' => '85250', 'name' => 'PAZ DE ARIPORO', 'department_id' => '85'],
            ['id' => '85263', 'name' => 'PORE', 'department_id' => '85'],
            ['id' => '85279', 'name' => 'RECETOR', 'department_id' => '85'],
            ['id' => '85300', 'name' => 'SABANALARGA', 'department_id' => '85'],
            ['id' => '85315', 'name' => 'SACAMA', 'department_id' => '85'],
            ['id' => '85325', 'name' => 'SAN LUIS DE PALENQUE', 'department_id' => '85'],
            ['id' => '85400', 'name' => 'TAMARA', 'department_id' => '85'],
            ['id' => '85410', 'name' => 'TAURAMENA', 'department_id' => '85'],
            ['id' => '85430', 'name' => 'TRINIDAD', 'department_id' => '85'],
            ['id' => '85440', 'name' => 'VILLANUEVA', 'department_id' => '85'],
            ['id' => '86001', 'name' => 'MOCOA', 'department_id' => '86'],
            ['id' => '86219', 'name' => 'COLON', 'department_id' => '86'],
            ['id' => '86320', 'name' => 'ORITO', 'department_id' => '86'],
            ['id' => '86568', 'name' => 'PUERTO ASIS', 'department_id' => '86'],
            ['id' => '86569', 'name' => 'PUERTO CAICEDO', 'department_id' => '86'],
            ['id' => '86571', 'name' => 'PUERTO GUZMAN', 'department_id' => '86'],
            ['id' => '86573', 'name' => 'LEGUIZAMO', 'department_id' => '86'],
            ['id' => '86749', 'name' => 'SIBUNDOY', 'department_id' => '86'],
            ['id' => '86755', 'name' => 'SAN FRANCISCO', 'department_id' => '86'],
            ['id' => '86757', 'name' => 'SAN MIGUEL', 'department_id' => '86'],
            ['id' => '86760', 'name' => 'SANTIAGO', 'department_id' => '86'],
            ['id' => '86865', 'name' => 'VALLE DEL GUAMUEZ', 'department_id' => '86'],
            ['id' => '86885', 'name' => 'VILLAGARZON', 'department_id' => '86'],
            ['id' => '88001', 'name' => 'SAN ANDRES', 'department_id' => '88'],
            ['id' => '88564', 'name' => 'PROVIDENCIA', 'department_id' => '88'],
            ['id' => '91001', 'name' => 'LETICIA', 'department_id' => '91'],
            ['id' => '91263', 'name' => 'EL ENCANTO', 'department_id' => '91'],
            ['id' => '91405', 'name' => 'LA CHORRERA', 'department_id' => '91'],
            ['id' => '91407', 'name' => 'LA PEDRERA', 'department_id' => '91'],
            ['id' => '91430', 'name' => 'LA VICTORIA', 'department_id' => '91'],
            ['id' => '91460', 'name' => 'MIRITI - PARANA', 'department_id' => '91'],
            ['id' => '91530', 'name' => 'PUERTO ALEGRIA', 'department_id' => '91'],
            ['id' => '91536', 'name' => 'PUERTO ARICA', 'department_id' => '91'],
            ['id' => '91540', 'name' => 'PUERTO NARIÑO', 'department_id' => '91'],
            ['id' => '91669', 'name' => 'PUERTO SANTANDER', 'department_id' => '91'],
            ['id' => '91798', 'name' => 'TARAPACA', 'department_id' => '91'],
            ['id' => '94001', 'name' => 'INIRIDA', 'department_id' => '94'],
            ['id' => '94343', 'name' => 'BARRANCO MINAS', 'department_id' => '94'],
            ['id' => '94663', 'name' => 'MAPIRIPANA', 'department_id' => '94'],
            ['id' => '94883', 'name' => 'SAN FELIPE', 'department_id' => '94'],
            ['id' => '94884', 'name' => 'PUERTO COLOMBIA', 'department_id' => '94'],
            ['id' => '94885', 'name' => 'LA GUADALUPE', 'department_id' => '94'],
            ['id' => '94886', 'name' => 'CACAHUAL', 'department_id' => '94'],
            ['id' => '94887', 'name' => 'PANA PANA', 'department_id' => '94'],
            ['id' => '94888', 'name' => 'MORICHAL', 'department_id' => '94'],
            ['id' => '95001', 'name' => 'SAN JOSE DEL GUAVIARE', 'department_id' => '95'],
            ['id' => '95015', 'name' => 'CALAMAR', 'department_id' => '95'],
            ['id' => '95025', 'name' => 'EL RETORNO', 'department_id' => '95'],
            ['id' => '95200', 'name' => 'MIRAFLORES', 'department_id' => '95'],
            ['id' => '97001', 'name' => 'MITU', 'department_id' => '97'],
            ['id' => '97161', 'name' => 'CARURU', 'department_id' => '97'],
            ['id' => '97511', 'name' => 'PACOA', 'department_id' => '97'],
            ['id' => '97666', 'name' => 'TARAIRA', 'department_id' => '97'],
            ['id' => '97777', 'name' => 'PAPUNAUA', 'department_id' => '97'],
            ['id' => '97889', 'name' => 'YAVARATE', 'department_id' => '97'],
            ['id' => '99001', 'name' => 'PUERTO CARREÑO', 'department_id' => '99'],
            ['id' => '99524', 'name' => 'LA PRIMAVERA', 'department_id' => '99'],
            ['id' => '99624', 'name' => 'SANTA ROSALIA', 'department_id' => '99'],
            ['id' => '99773', 'name' => 'CUMARIBO', 'department_id' => '99'],
        ];

        DB::table('departments')->insert($departments);
        DB::table('municipalities')->insert($municipalities);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
